### ISSUE TITLE
Implement retransmissions

### ISSUE THREAD

**Issue by jlaine** [aiortc/aioquic#1]
Currently aioquic performs no retransmissions, meaning it cannot deal with packet loss.

See:
https://tools.ietf.org/html/draft-ietf-quic-transport-20#section-13.2

**Comment by jlaine** [comment]
This is now fixed!

**Comment by Alrobbertz** [comment]
I was testing this implementation within two containers talking to each other on a docker network. I was simulating various stressful network conditions using the linux trafic control tool and found that the client and server connection hangs up and stops transmitting packages when there is relatively little (10%) loss on the network. I'm not sure the cause of this issue, but I will investigate further and try to provide more details.

**Comment by jlaine** [comment]
Does the transfer stall after receiving some data or no data at all? Currently retransmissions *should* be working well for the 1-RTT epoch ("application data"), however the earlier phases (INITIAL + HANDSHAKE) are currently missing retransmissions, so it's possible for the connection to stall at the very beginning

**Comment by Alrobbertz** [comment]
It stalls after a successful handshake and receiving some data. The test sends encoded images over multiple streams so the stress and loss conditions may just overwhelm the simulated docker network. I will do more tests and try to determine the cause.

**Comment by jlaine** [comment]
OK I found and fixed some logic errors, re-transmission of app data should work reliably. There is a unit test which exercises this with a 25% packet loss here:

https://github.com/aiortc/aioquic/blob/e94acbda71214eac74f61e0d3a5944c87a03c37a/tests/test_connection.py#L875

Re-transmission of initial / handshake packets is starting to work, but it's not finished yet.

Neertheless could you try again and let me know if you see an improvement?

**Comment by Alrobbertz** [comment]
I conducted the same test on the updated version and noticed much better performance. I did not encounter any lost connections in tests with both high loss and latency. It looks so far like all issues have been fixed.
