### ISSUE TITLE
API for resetting streams

### ISSUE THREAD

**Issue by vasilvv** [aiortc/aioquic#100]
Currently, aioquic informs the application whenever the peer resets the stream, but there is no way for the application to reset a stream on its side.  Ideally, that would also result in the stream data not being retransmitted if lost and the stream is already reset.

**Comment by jlaine** [comment]
Right there is currently no API to reset a stream, what should it look like in your opinion.

I'm sorry but I didn't understand your second sentence, any chance of rephrasing it?

**Comment by vasilvv** [comment]
I think just `reset_stream(stream_id: int, reset_code: int)` should be fine.

> I'm sorry but I didn't understand your second sentence, any chance of rephrasing it?

Sorry, I think I got confused.  Ignore that.

**Comment by jlaine** [comment]
OK, the API looks short and sweet, let's go with that.

**Comment by jlaine** [comment]
An initial API was merged in #110 with the suggested API
