### ISSUE TITLE
integrating quantum ciphers into QUIC

### ISSUE THREAD

**Issue by prchander** [aiortc/aioquic#102]
Hello, this is a question not an issue. Aioquic uses OpenSSL but I was wondering if there was something that I could do to get Open Quantum Safe OpenSSL to work with QUIC (https://github.com/open-quantum-safe/openssl). Is it just linking pip to the OQS OpenSSL when it installs or is the process much harder?

Thank you

**Comment by jlaine** [comment]
Correction: `aioquic` only uses OpenSSL's primitives, it does not use its TLS engine at all. I'm not sure what you're trying to do, but feel free to submit a PR.

**Comment by prchander** [comment]
Thank you for your reply. I am just thinking if it should be okay just swapping the directory of OpenSSL that aioquic uses to QOS OpenSSL to see if it will start recognizing the new ciphers. 

Thank you.

**Comment by jlaine** [comment]
My point is the opposite: I don't think you need a patched OpenSSL at all, you should be able to tap straight into liboqs (you'll need to write some C code). A patched OpenSSL won't give you anything, as we don't use its TLS engine at all.

**Comment by prchander** [comment]
So you think just linking it to OQS with a program should do the trick? Thank you for all the help @jlaine I have been using and working on aioquic for 6 months and it is amazing.
