### ISSUE TITLE
Change frame contents

### ISSUE THREAD

**Issue by kangprog** [aiortc/aioquic#108]
Hello, I would like to test the frame content change. For example, change the maximum data value of MAX DATA Frame arbitrarily.

Could you please change from http3client.py and provide tips on how to test it?

**Comment by jlaine** [comment]
I'm sorry but I don't understand what you want from me: you have the full source code, feel free to make any changes you need.

**Comment by kangprog** [comment]
Sorry. 

I want to reproduce security considerations 12-2 in draft28.

Can I send a NEW_CONNECTION_ID frame?

**Comment by jlaine** [comment]
`git grep NEW_CONNECTION_ID` :)

**Comment by kangprog** [comment]
An error occurred while sending the initial packet.

I tried to send only the initial packet among pcaps obtained when executing example/httpclient.

When using sendto(<Raw Data>,(<http3_server IP>, 4433)) of socket module, the server responds. However, when using sendp(<InitialPacket>) of the scapy module, there is no response from the server.

Do you know why?
