### ISSUE TITLE
investigate performance and optimize

### ISSUE THREAD

**Issue by jlaine** [aiortc/aioquic#11]
To have a consistent basis for testing, here is how I run my tests.

# Launch the server

`python examples/server.py -c tests/ssl_cert.pem -k tests/ssl_key.pem`

# Launch a client

## aioquic

Download 50MB of data using `aioquic`:

`python examples/client.py 127.0.0.1 4433 /50000000 > /dev/null`

The download throughput will be displayed

## picoquic

To only test the server it can be useful to use a different client, for instance picoquic which has good and consistent performance.

`picoquicdemo -a hq-20 -v ff000014 127.0.0.1 4433 0:/50000000`

**Comment by njsmith** [comment]
I wonder if there's any easy way to include latency in your benchmarking measurements. There's a neat talk on latency measurement here: https://www.infoq.com/presentations/latency-pitfalls

**Comment by jlaine** [comment]
Current performance is acceptable, I reliably get > 150Mbps per core for HTTP/3, so I will close this issue for now. We can always re-open an issue if additional optimization opportunities are identified.
