### ISSUE TITLE
Custom Congestion Control

### ISSUE THREAD

**Issue by Leo-rojo** [aiortc/aioquic#117]
Hi, 
I was wandering if there is an easy way to change the current congestion control algorithm with a custom one. I've taken a quick look at the code but I haven't seen an easy way to do that.

**Comment by jlaine** [comment]
Currently there isn't an "easy way" to change the congestion controller. However, all the New Reno congestion controller is implemented in `src/aioquic/quic/recovery.py`, specifically the `QuicCongestionControl` class. You should be able to replace this by whatever other congestion controller you wish to implement. I'd appreciate it if you kept me informed of how this goes, as I don't yet have confirmation that the API is sufficiently generic. Once we have 2 or more implementations we can add an option to choose the congestion controller.

**Comment by honglei** [comment]
like lsquic ? 
https://github.com/litespeedtech/lsquic/blob/master/src/liblsquic/lsquic_bbr.c#L1069 
```C
const struct cong_ctl_if lsquic_cong_bbr_if =
{
    .cci_ack           = lsquic_bbr_ack,
    .cci_begin_ack     = lsquic_bbr_begin_ack,
    .cci_end_ack       = lsquic_bbr_end_ack,
    .cci_cleanup       = lsquic_bbr_cleanup,
    .cci_get_cwnd      = lsquic_bbr_get_cwnd,
    .cci_init          = lsquic_bbr_init,
    .cci_pacing_rate   = lsquic_bbr_pacing_rate,
    .cci_loss          = lsquic_bbr_loss,
    .cci_lost          = lsquic_bbr_lost,
    .cci_reinit        = lsquic_bbr_reinit,
    .cci_timeout       = lsquic_bbr_timeout,
    .cci_sent          = lsquic_bbr_sent,
    .cci_was_quiet     = lsquic_bbr_was_quiet,
};
```
Or msvft
https://github.com/facebookincubator/mvfst/blob/master/quic/state/StateData.h#L212

```C
struct CongestionController {
  // Helper struct to group multiple lost packets into one event
  struct LossEvent { 
  };

  struct AckEvent {
   
  };  

  virtual void onRemoveBytesFromInflight(uint64_t) = 0;
  virtual void onPacketSent(const OutstandingPacket& packet) = 0;
  virtual void onPacketAckOrLoss(
      folly::Optional<AckEvent>,
      folly::Optional<LossEvent>) = 0;
}
```
