### ISSUE TITLE
QUIC packet size

### ISSUE THREAD

**Issue by alexpresss** [aiortc/aioquic#123]
Hi

I'm using aioquic in my master thesis to compare the different HTTP versions to each other and how well these perform.
I would like to know if it is possible to change the size of the QUIC packets cause I have experienced performance issues with big files with HTTP/3 compared to HTTP/1.1. I have sifted through all the code but haven't found any possibility yet...

Kind Regards
Alexander

**Comment by jlaine** [comment]
You can try tinkering with:

https://github.com/aiortc/aioquic/blob/b0c8dda546a6f97fe125309999010c0c71e5e992/src/aioquic/quic/packet_builder.py#L20
