### ISSUE TITLE
Access the example server's HTML page through Chrome

### ISSUE THREAD

**Issue by Geshode** [aiortc/aioquic#127]
I found, that there is a sample html page (index.html) inside the templates folder inside the examples. 

Is it supposed to be possible to access it with Chrome through https://localhost:4433/ ?
Because I tried that, while having the Experimental QUIC protocol flag enabled, but I only get the error message, that the site could not be reached.

**Comment by jlaine** [comment]
I cannot remember how to invoke Chrome with the right flags, as it will almost certainly refuse the certificate. Could you try against https://quic.aiortc.org/ ?

**Comment by jlaine** [comment]
With the latest stable Chrome I can trigger a QUIC/HTTP3 connection using:

`google-chrome --origin-to-force-quic-on=localhost:4433 https://localhost:4433/`

.. however Chrome will fail to load the page, as the certificate is (rightly) not recognised as valid.

**Comment by jlaine** [comment]
Update: I can get the page to load using:

`google-chrome --ignore-certificate-errors-spki-list=BSQJ0jkQ7wwhR7KvPZ+DSNk2XTZ/MS6xCbo9qu++VdQ= --origin-to-force-quic-on=localhost:4433 https://localhost:4433/`

Where the fingerprint of the certificate was obtained using:

`openssl x509 -in tests/ssl_cert.pem -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64`
