### ISSUE TITLE
Data corruption upon packet loss recovery

### ISSUE THREAD

**Issue by huitema** [aiortc/aioquic#128]
@jlaine  I have been looking again at the failure seen in the interop runner -- logs [here](https://interop.seemann.io/logs_2020-07-21T09:21:15UTC/picoquic_aioquic/crosstraffic/). These failure seems to happen regularly during the "cross traffic" tests between aiortc client and picoquic server.

The downloaded file differs from the reference file. I compared the two files, and I find the following:

1. The two files have the same length, but the contents differ after offset 19238721
2. After that point, all the bytes in the downloaded file appear different from the reference file
3. The data at offset 19238721 was transmitted in packet number 13821, which was correctly received at T=19817.26
4. However, the packet 13820 before that was lost.
5. The content of 13820 was re-transmitted later, split in two packets
6. Packet 13860, received at T=19855.18 contains 1397 bytes of data from offset= 19237315
7. Packet 13861, received at T= 19856.3 contains 9 bytes of data from offset=19238712

It appears that something got wrong on the client after receiving these corrected bytes, leading to receiving a corrupted file.

Maybe you want to fix that...

**Comment by jlaine** [comment]
Hi @huitema, I'm progressively trying to get back afloat on my various opensource projects, so sorry for not answering sooner.

Thanks for taking the time to dive into the problem, this definitely sounds like something that needs fixing.

The lgos have unfortunately expired meanwhile, I'll try looking for similar errors in more recent logs.

**Comment by jlaine** [comment]
@huitema to the best of my knowledge this is now fixed
