### ISSUE TITLE
QNS C1 fails with Neqo client -- client never gets HandshakeDone frame

### ISSUE THREAD

**Issue by agrover** [aiortc/aioquic#129]
[aioquic-neqo-c1-fail.zip](https://github.com/aiortc/aioquic/files/5037416/aioquic-neqo-c1-fail.zip)

Hi, Neqo is seeing intermittent failures with the interop runner for C1 and L1 tests (client=Neqo, server=aioquic). Attached log is of a session where we caught it, for connection 74cd5708e248465dbb1c57d74aae59d83e.

We can see the server send HandshakeDone frames twice (server 1RTT:14 and 1RTT:16). Client ACKs indicating 14 and 16 were lost (in client 1RTT:5,6,7) are all not received.

This scenario doesn't happen often, but it does happen, and wanted to open an issue so it could get a little attention. I don't see any place where either end is not meeting the spec, but I wonder if there are things that could be done to make connection establishment more bulletproof in this scenario. For example, if server PTO sends two packets, and/or includes unacked data.

**Comment by jlaine** [comment]
Thanks for the taking the time to analyse this behaviour Andy! @huitema made a similar observation, it sounds as though I need to revisit the PTO code.

**Comment by jlaine** [comment]
@agrover this should be fixed by PR #265. aioquic will now more agressively retransmit CRYPTO data during handshake
