### ISSUE TITLE
ECN support

### ISSUE THREAD

**Issue by larseggert** [aiortc/aioquic#131]
Would be great if aioquic would mark its packets with ECT(0) and would report ACK-ECN frames.

**Comment by jlaine** [comment]
I have previously looked into this and unfortunately I don't think this is possible with the socket APIs provided by Python.

I'd love to be proven wrong though!

**Comment by larseggert** [comment]
https://pypi.org/project/nadds/ seems to be a python2 module supporting cmsg ancillary data, and the page says that python3 should have this natively? Of course that may be wrong and/or not working.

**Comment by jlaine** [comment]
Hi @larseggert I'm sorry but I haven't found a way to support ECN so I'm going to close this as "wontfix".

**Comment by felixshing** [comment]
So, currently, airtoc still does not support ECN and L4S?

**Comment by rthalley** [comment]
Correct.   I'll take another look at it and see if I can figure out how to get and set the info in python.
