### ISSUE TITLE
Possible mistake when handling a duplicate frame

### ISSUE THREAD

**Issue by arut** [aiortc/aioquic#134]
I've been looking at interop failures of auiquic + nginx and found what could be the reason of it. When a duplicate frame is handled in `add_frame()`, the `count` does not get decreased, which may further lead to cutting a part of the buffer at the front.

Handling an old frame:
https://github.com/aiortc/aioquic/blob/919ccec9836bf5fa4329b5b050604b09f71d0bdc/src/aioquic/quic/stream.py#L82

Cutting the buffer:
https://github.com/aiortc/aioquic/blob/919ccec9836bf5fa4329b5b050604b09f71d0bdc/src/aioquic/quic/stream.py#L95

**Comment by jlaine** [comment]
Thanks for this, this looks like the likely root cause for #128. I will try to look at this at the latest over the weekend
