### ISSUE TITLE
Integration with Django?

### ISSUE THREAD

**Issue by asencis** [aiortc/aioquic#137]
I'm just glancing over this repository - looks awesome! Can it (I assume it can) integrate with a recent version of Django? >3 with Python >3.9?

If so...how? :D

**Comment by pgjones** [comment]
You can use [Hypercorn](https://gitlab.com/pgjones/hypercorn) (which uses this project) with Django, see the [docs](https://docs.djangoproject.com/en/3.1/howto/deployment/asgi/hypercorn/).

**Comment by jlaine** [comment]
@asencis the answer from @pgjones is spot on, the most mature ASGI server which leverages aioquic is indeed hypercorn.
