### ISSUE TITLE
What is the protocol reference?

### ISSUE THREAD

**Issue by louisabraham** [aiortc/aioquic#14]
Hi, I'm discovering this nice project. I have hoping to see a reference for the protocol. I found <https://tools.ietf.org/html/draft-tsvwg-quic-protocol-02> but I think this is not the same (for example, I don't think the "public flags" described there are the same as `first_byte` read in `pull_quic_header`).
Therefore, could you please make explicit what reference is followed?

**Comment by jlaine** [comment]
The current IETF draft for QUIC is here: https://tools.ietf.org/html/draft-ietf-quic-transport-20
