### ISSUE TITLE
localhost not running from Browser ?

### ISSUE THREAD

**Issue by abnvsally** [aiortc/aioquic#145]
Hi
    I'm not able to open the index.html on browser like chrome canary etc. After enabling quic in canary when I try to run https://localhost:4433/ in the browser. It says site cannot be reached. Can you help me where I'm going wrong. 

Thanks

**Comment by jlaine** [comment]
Chrome will not initially attempt HTTP/3, it will try a regular HTTP request and switch to HTTP/3 if the server announces support for it. This does not work if the server is HTTP/3 only.

See #127 for the appropriate flags to force HTTP/3 and accept the certificate
