### ISSUE TITLE
No packet header encryption

### ISSUE THREAD

**Issue by simonasmulevicius** [aiortc/aioquic#149]
Good morning, 

I am doing a research project about the QUIC offloading in hardware.
For this reason, I would like to be able to see packet numbers (in hardware).
However, I know that multiple implementations of QUIC usually encrypt packet headers.
Hence, I wonder if this implementation of QUIC has an API to turn off packet header encryption mechanism.

Kind regards, 
Simonas

**Comment by jlaine** [comment]
Hi, there is no API to switch off packet header protection. However you could quite easily patch `src/aioquic/quic/crypto.py` to short-circuit the packet header protection / unprotection code.

**Comment by simonasmulevicius** [comment]
By the way, is it possible to join your Slack chat? I would like to hear some tips about the testing of aioquic.

**Comment by jlaine** [comment]
The only Slack chat would be the one of the Quic Working Group, you'd have to ask those in charge: https://quicwg.org/
