### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement quic_logger

### ISSUE THREAD

**Issue by binarytrails** [aiortc/aioquic#151]
```
$ pip install quic_logger
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement quic_logger (from versions: none)
ERROR: No matching distribution found for quic_logger
$ pip --version
pip 20.1.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by jlaine** [comment]
I'm not sure I understand this issue, what is this package you are trying to install?

**Comment by binarytrails** [comment]
@jlaine quite valid as back in the days of my issue check your examples:
```from quic_logger import QuicDirectoryLogger```
https://github.com/aiortc/aioquic/blob/main/examples/http3_server.py#L12

**Comment by jlaine** [comment]
https://github.com/aiortc/aioquic/blob/main/examples/quic_logger.py
