### ISSUE TITLE
Why does interop show all server-role IPv6 tests as failures?

### ISSUE THREAD

**Issue by jimmbelll** [aiortc/aioquic#152]
Why does the [interop matrix](https://interop.seemann.io/) show all server-role IPv6 tests as failed?  You seem to support IPv6, and pass most of the **_`6`_** tests in the client role.

**Comment by jlaine** [comment]
No idea, I'm puzzled by this too. You are welcome to investigate and report back!

**Comment by jlaine** [comment]
It looks a though it was "just" a case of updating the base Docker image.
