### ISSUE TITLE
low transport speed 

### ISSUE THREAD

**Issue by yc1997427** [aiortc/aioquic#153]
Hi,

I run the server and client on local machines, but I found that the transport speed is very low, when I transport 50MB, the speed is just around 90Mbps. I'm wondering if this is the usual speed of aioquic or is there anything I need to change.

**Comment by jimmbelll** [comment]
The [interop performance measurements table](https://interop.seemann.io/#measurements) shows lots of speed test results. 9Mbps seems pretty standard.

**Comment by yc1997427** [comment]
Hi, thanks for the resources. And may I ask is there way to run the binary of the client and server? Since I want to use perf to test the CPU uages of aioquic, but running with python might hide the CPU usages of aioquic.

**Comment by ihlar** [comment]
I've performed similar tests with this stack and max out around 90MB/s as well (client and server on the same machine, sending over the loopback interface). 
It is the CPU that is the bottleneck in my case. 

> The [interop performance measurements table](https://interop.seemann.io/#measurements) shows lots of speed test results. 9Mbps seems pretty standard.

These tests are performed over a simulated link with a 10 Mb/s bandwidth.

**Comment by jlaine** [comment]
I seem to be missing your PR which delivers an amazing improvement, all I see is the negative comment?
