### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by NostalgiaRunner** [aiortc/aioquic#157]
The title says it all. This looks like a really great library and I'd love to use it. However, the http3 client is not h3-29 compatible with https://http3.is, and the http3 server is not usable by the Chrome browser. My error seems to be related to QPack compression not decompressing validly. But lots of other people are having issues with this project for the next few months, and I've seen little to no responses to issues that have decently descriptive reports. Is this project still active?
Thank you.

**Comment by jlaine** [comment]
My time is limited at the moment but pull requests are welcome.
