### ISSUE TITLE
client.py not working

### ISSUE THREAD

**Issue by PrivateRyan94** [aiortc/aioquic#16]
Hi,
I'm not able to run the client-script...
When I start the Client, I get an AttributeError: X962
`Traceback (most recent call last):`
`  File "examples/client.py", line 106, in <module>`
`    session_ticket_handler=save_session_ticket,`
`  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete`
`    return future.result()`
`  File "examples/client.py", line 30, in run`
`    async with connect(host, port, **kwargs) as connection:`
`  File "/usr/lib/python3.7/contextlib.py", line 170, in __aenter__`
`    return await self.gen.__anext__()`
`  File "/home/ryan/Seafile/Masterarbeit/QUIC-Projekt-aioquic/aioquic/aioquic/asyncio/client.py", line 84, in connect`
`    protocol.connect(addr, protocol_version)`
`  File "/home/ryan/Seafile/Masterarbeit/QUIC-Projekt-aioquic/aioquic/aioquic/asyncio/protocol.py", line 61, in connect`
`    addr, now=self._loop.time(), protocol_version=protocol_version`
`  File "/home/ryan/Seafile/Masterarbeit/QUIC-Projekt-aioquic/aioquic/aioquic/connection.py", line 446, in connect`
`    self._connect(now=now)`
`  File "/home/ryan/Seafile/Masterarbeit/QUIC-Projekt-aioquic/aioquic/aioquic/connection.py", line 867, in _connect`
`    self.tls.handle_message(b"", self._crypto_buffers)`
`  File "/home/ryan/Seafile/Masterarbeit/QUIC-Projekt-aioquic/aioquic/aioquic/tls.py", line 1077, in handle_message`
`    self._client_send_hello(output_buf[Epoch.INITIAL])`
`  File "/home/ryan/Seafile/Masterarbeit/QUIC-Projekt-aioquic/aioquic/aioquic/tls.py", line 1192, in _client_send_hello`
`    key_share.append(encode_public_key(self._ec_private_key.public_key()))`
`  File "/home/ryan/Seafile/Masterarbeit/QUIC-Projekt-aioquic/aioquic/aioquic/tls.py", line 927, in encode_public_key`
`    public_key.public_bytes(Encoding.X962, PublicFormat.UncompressedPoint),`
`  File "/usr/lib/python3.7/enum.py", line 349, in __getattr__`
`    raise AttributeError(name) from None`
`AttributeError: X962`

After `git clone ...`, I run `pip3 install -e .` ... Am I missing something?

**Comment by honglei** [comment]
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.Encoding

try update lib cryptography to >=2.5

**Comment by honglei** [comment]
The requirements/doc.txt should be changed accordingly.
`
cryptography >=2.5
`

**Comment by jlaine** [comment]
The `requirements/doc.txt` is only used for the automated documentation builds, but I've added the versioned dependency on cryptography in `setup.py`

**Comment by PrivateRyan94** [comment]
thx. :)
