### ISSUE TITLE
Is it possible to serve pages using H2 on AIOQUIC ? 

### ISSUE THREAD

**Issue by abnv418** [aiortc/aioquic#161]
I wanted to know if AIOQUIC server can serve pages on H2. I know AIOQUIC is H3 based. This question is in regards to serving the same content that is served on H3 to compare the performance on H2. As this kind of patch is available for QUICHE on 
https://blog.cloudflare.com/experiment-with-http-3-using-nginx-and-quiche/

Any guidance will be helpful. 

Thanks.

**Comment by jlaine** [comment]
The aioquic codebase is exclusively focused on HTTP/3 as there is already well established Python code for handling other HTTP versions.

 If you want a webserver which handles HTTP/1.1, HTTP/2 and HTTP/3 take a look at hypercorn, which leverages aioquic for its HTTP/3 support: https://pgjones.gitlab.io/hypercorn/

**Comment by abnv418** [comment]
Thanks. it was really helpful. Is there a docker version of AIOQUIC enabled hypercorn ?

**Comment by jlaine** [comment]
Sorry, no idea there!

**Comment by pgjones** [comment]
[This](https://gitlab.com/pgjones/pgjones_dev/-/blob/master/Dockerfile) is an example, I use it for [pgjones.dev](https://pgjones.dev)

**Comment by abnv418** [comment]
Thanks. 👍
