### ISSUE TITLE
Multiple entries in server._protocols for same connection

### ISSUE THREAD

**Issue by dimitsqx** [aiortc/aioquic#162]
Why does a server keep in self._protocols multiple CIDs that point to the same QuicConnectionProtocol?

**Comment by jlaine** [comment]
I'm not sure I understand your question, but here goes anyway. The local endpoint issues multiple CIDs which the remote party can use, this is needed for connection migrations. We need to route any packet addressed to these CIDs to the correct protocol.

Does this answer your question?

**Comment by dimitsqx** [comment]
Yes, thanks
