### ISSUE TITLE
[design] remove QuicConnectionProtocol.create_stream() ?

### ISSUE THREAD

**Issue by jlaine** [aiortc/aioquic#169]
The `QuicConnectionProtocol.create_stream()` method was added to the API early on in the project to provide a way to create a raw pair of reader / writers. However, I have since realised that this is a very niche case, none of the examples use this API. It is more powerful to tap into the `quic_event_received()` callback.

Similarly the following should probably go:

- the `stream_handler` argument to `client.connect()`
- the `stream_handler` argument to `server.listen()`

**Comment by jmgurney** [comment]
Please don't remove this.  I just added quic support to ntunnel and am using them.  It save the work of having to demux the data, and makes using this integrate nicely with programs that are already designed to use asyncio.open_connection (https://docs.python.org/3/library/asyncio-stream.html#asyncio.open_connection)
