### ISSUE TITLE
Creating Multiple streams from Client

### ISSUE THREAD

**Issue by dimitsqx** [aiortc/aioquic#170]
What I see in the current implementation is when you create a stream from the client-side by calling:
https://github.com/aiortc/aioquic/blob/c99b43f4c7a1903e9ab2431932395bb7e0b29232/src/aioquic/asyncio/protocol.py#L63-L75

You get the stream_id and create a reader, writer object, however, you don't create a new entry in QuicConnection._streams. When a new stream is created it gets the same stream_id of 0 because there are no entries in QuicConnection._streams. I believe the create_stream should also call: 
https://github.com/aiortc/aioquic/blob/c99b43f4c7a1903e9ab2431932395bb7e0b29232/src/aioquic/quic/connection.py#L1157-L1197

**Comment by jlaine** [comment]
See #169, I'm considering removing this API completely. I'm sure there is a usecase for exposing raw QUIC streams as python stream readers / writers

**Comment by bootcap** [comment]
Could you please tell me if the create_stream API is still available now?

I want to create multiple streams in my experiment to measure how the number of streams affects transmission speed in various network states. I noticed a create_stream() in Asyncio API, but there are no examples. I suppose create_stream should be part of the basic Quic Protocol, but there is no such a create_stream in QUIC API. Why?
