### ISSUE TITLE
Can server create stream?

### ISSUE THREAD

**Issue by 873314461** [aiortc/aioquic#18]
Hi,
    I am using aioquic to develop a software. I want to create a one-way stream from the server to transfer data in the existing session, but I don't seem to find a way to create a stream on the server.
    Who can give me a solution?
Thanks.

**Comment by jlaine** [comment]
I'm not sure what you mean by "a server" as aioquic offers multiple APIs.

Assuming we are speaking about the asyncio server API, no there isn't a convenient way. However you can look at the http3-server example which builds directly on QuicConnection and does create unidirectional streams.

**Comment by jlaine** [comment]
It is now possible to specify your own factory for `QuicConnectionProtocol` using the `create_protocol` argument to `serve`, so this is now possible:

https://aioquic.readthedocs.io/en/latest/asyncio.html#aioquic.asyncio.serve
