### ISSUE TITLE
How can l test the connection migration?

### ISSUE THREAD

**Issue by machao0322** [aiortc/aioquic#185]
Thanks for your contribution.
Can you tell me how to test the connection migration?

**Comment by machao0322** [comment]
I tried to change the server IP when runing "python examples/http3_server.py ..."， but sadly,  the connection migration does not work.

**Comment by jlaine** [comment]
Hi! The easiest way to test connection migration is for the client to change the port it uses during the lifetime of the connection.

There isn't a public / documented API but you can do the same as the `interop.py` does, and replace the transport (socket) used by the client:

https://github.com/aiortc/aioquic/blob/9f84c91853207355f534b42568ac961e1b800608/examples/interop.py#L357-L359

**Comment by machao0322** [comment]
Glad to receive your reply! It is a great help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jeremy ***@***.***&gt;; 
发送时间: 2021年7月8日(星期四) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aiortc/aioquic] How can l test the connection migration? (#185)





 
Hi! The easiest way to test connection migration is for the client to change the port it uses during the lifetime of the connection.
 
There isn't a public / documented API but you can do the same as the interop.py does, and replace the transport (socket) used by the client:
 
https://github.com/aiortc/aioquic/blob/9f84c91853207355f534b42568ac961e1b800608/examples/interop.py#L357-L359
