### ISSUE TITLE
How can I manually close a stream (by using STOP_SENDING) without closing the connection

### ISSUE THREAD

**Issue by Yang-Jace-Liu** [aiortc/aioquic#186]
Hello,

Thank you for making this awesome library. I'm new to QUIC but I do encounter some problems. As the title said, how can I manually send a STOP_SENDING frame to close a specific stream without stopping the whole connection.

According to [QUIC draft Sec. 11.2](https://www.ietf.org/archive/id/draft-ietf-quic-transport-34.html#name-stream-errors), The application could close only one stream and at the same time keep other streams open.

Currently, I manually constructed a STOP_SENDING frame and sent it by using `QuicConnectionProtocol.transmit()`. However, moments after sending out the frame, one message showed on the screen:
```
INFO:quic:[2c2a916354cb7377] Connection close received (code 0x1, reason )
DEBUG:quic:[2c2a916354cb7377] QuicConnectionState.CONNECTED -> QuicConnectionState.DRAINING
```
Clearly, the connection gets closed. What should I do to close one stream without closing the connection?

The server is the latest Nginx-quic snapshot.

Thank you in advance.

Edit: Typo

------

Code of constructing the STOP_SENDING frame and sending it out
```python
async def close_stream(stream_id):
    self._quic.send_datagram_frame(_encode_stop_sending_frame(stream_id))
    self.transmit()


def _encode_stop_sending_frame(stream_id) -> bytes:
    b = bytearray()
    b.extend(encode_variable_length_integer(0x05))  # TYPE: STOP_SENDING
    b.extend(encode_variable_length_integer(stream_id)) # STREAM ID
    b.extend(encode_variable_length_integer(0)) # READON: NO_ERROR
    return bytes(b)

def encode_variable_length_integer(num: int) -> bytes:
    if num <= 63:
        return bytes([num])
    elif num <= 16383:
        b = num.to_bytes(2, byteorder='big')
        b[0] |= 0x40
        return b
    elif num <= 1073741823:
        b = num.to_bytes(4, byteorder='big')
        b[0] |= 0x80
        return b
    else:
        b = num.to_bytes(8, byteorder='big')
        b[0] |= 0xC0
        return b
```

**Comment by a3y3** [comment]
I'm pretty new to this library too so I could be wrong/misunderstanding but there's an `end_stream` bool flag  in the `send_stream_data` method.

**Comment by Yang-Jace-Liu** [comment]
@a3y3 Thank you for your response. the `send_stream_data` is to send the STREAM frame, and I need to send the STOP_SENDING frame. `end_stream` is to set an EOF to the STREAM frame. Thank you anyway.

I made some changes to the library at my end, adding some code similar to how `QuicConnection::reset_stream()` got handled. It's working (I guess).
