### ISSUE TITLE
ModuleNotFoundError: No module named 'aioquic._buffer'

### ISSUE THREAD

**Issue by machao0322** [aiortc/aioquic#187]
1

**Comment by machao0322** [comment]
aioquic version: 0.9.11
centOS 7 System
python 3.6

Maybe the aioquic directory should not be contained in examples/. Otherwise, an error mentioned above will occur. Even if “pip install -e .” is performed, the _buffer can not be found in aioquic.

**Comment by machao0322** [comment]
I solved the problem by renaming the aioquic directory in example directory.

**Comment by machao0322** [comment]
close

**Comment by machao0322** [comment]
I made a mistake.

**Comment by leeliliang** [comment]
> I made a mistake.
what mistake? i have same issue with pycharm
@machao0322

**Comment by jlaine** [comment]
My guess would be that the package was not installed. Try `pip install -e .`

**Comment by leeliliang** [comment]
> My guess would be that the package was not installed. Try `pip install -e .`

Thank you for your reply, but not really,  aioquic has been installed,  run the code  in terminal successfully.

/Users/mac/.conda/envs/aioquic/bin/python /Users/mac/python/aioquic/examples/http3_client.py --ca-certs tests/pycacert.pem  https://localhost:4433/
but running with pycharm always error,  i am a noob with pycharm
i think that i should ask the question pycharm issues，sorry to bother you
![C5CE07E7-BFCC-4B1D-BB64-E1FEB48DDB1F](https://user-images.githubusercontent.com/49196656/127297128-de5e86ca-d9fe-4617-bd02-63a389014a3e.png)

**Comment by leeliliang** [comment]
> pip install -e .
thanks a lot, it works for me
