### ISSUE TITLE
Is here a simple socket api for quic which tcp have had?

### ISSUE THREAD

**Issue by FlyChenKai** [aiortc/aioquic#188]
Hello, i want a simple  socket api for quic, just like this:
```
socket = socket(addr, port)
socket.send(data)
```
but i don't find it in aioquic.
did i miss it?

Thank you!

**Comment by a3y3** [comment]
I had the same question as you. 
QUIC doesn't work exactly like TCP does, so you need something a little more than just a simple socket api. You should look at the issue I created and the discussion that followed here: https://github.com/aiortc/aioquic/issues/183
Looks like you're looking for the same thing I was, so lemme know if you have specific questions and I can try to help you :)

**Comment by FlyChenKai** [comment]
Thank you very much for your reply!
#183 really help me a lot, and I'm studying the doq_client.py and doq_server.py now.
Then I will try write a simple c/s communication  by it.
