### ISSUE TITLE
[Idea] FastAPI Integration

### ISSUE THREAD

**Issue by johnthagen** [aiortc/aioquic#196]
I see the example demo is using `starlette` for its `app`. Given [FastAPI](https://fastapi.tiangolo.com/) is built on top of `starlette`, would it be feasible to create a FastAPI example on top of `aioquic`? I could see this as being very interesting.

**Comment by johnthagen** [comment]
It turns out this *just works* because the `FastAPI` class is derived from the `Starlette` class.

Drop this into `demo.py`:

```py
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello World"}
```

**Comment by jlaine** [comment]
OK, I don't really see what we gain from this : you can just use any ASGI framework you like.

**Comment by johnthagen** [comment]
@jlaine Agreed. Hopefully if someone has a similar question, they'll find this issue and see it's possible to use FaatAPI if they want.
