### ISSUE TITLE
File "setup.py" not found.

### ISSUE THREAD

**Issue by bw1109** [aiortc/aioquic#199]
while running this command, 'RUN pip3 install -e .' in a Dockerfile, I am getting this error:
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /src
The command '/bin/sh -c pip3 install -e .' returned a non-zero code: 1

I have already done git clone from the original repository and the folder is present in the cloned folder, still it's giving me this error. Please Help!
How can we resolve this?

**Comment by jlaine** [comment]
This looks like a docker-specific issue (permissions?), I cannot help you here,
