### ISSUE TITLE
Split the `cryptography` (and other?) typestubs into independent repo?

### ISSUE THREAD

**Issue by wiml** [aiortc/aioquic#20]
Following [your comment in the pyca/cryptography issue tracker](https://github.com/pyca/cryptography/issues/4275#issuecomment-492023267) I was looking at merging your cryptography typestubs with the ones I've been incrementally generating for my own use. It would be handy if the typestubs were in their own git repository so that I could clone it locally and submit PRs against it and so on.

**Comment by jlaine** [comment]
I have proposed a PR to include the cryptography stubs in typeshed:

https://github.com/python/typeshed/pull/3307

**Comment by jlaine** [comment]
The PR I mentioned has been merged, so the type stubs for cryptography will be available in the next mypy release.
