### ISSUE TITLE
Size of encoded packet number fixed to 2?

### ISSUE THREAD

**Issue by vukasink** [aiortc/aioquic#200]
Hi all,
Excuse me if this is not the right place for my question, but I could not find a mailing list, or something similar.

It seems to me that size of the encoded packet number that goes into the header is 2 bytes.
Could you give me an intuition why is it fixed to 2 bytes, and not 1, or 3, or 4 as RFC allows?

Thanks,
Vukasin

**Comment by jlaine** [comment]
Hi!

To be clear: on the receive side aioquic supports decoding any valid packet number size.

On the send side however, setting a fixed length makes the code much simpler. I settled on 2-bytes as this was the most common value I found in other stacks.
