### ISSUE TITLE
UDP port exhaustion?

### ISSUE THREAD

**Issue by yctwo** [aiortc/aioquic#201]
While testing `aioquic` to send a lot of requests, I noticed that it starts getting exceptions after a while, and discovered that all the ephemeral UDP ports are exhausted. The faster it sends out the requests, the faster the exhaustion occurs.

It appears that the UDP socket is [not closed properly](https://docs.python.org/3/library/asyncio-protocol.html#udp-echo-client) in the `try-finally` block at the end of `asyncio/client.py` `connect()` function. Adding `transport.close()` does indeed solve the exhaustion issue, but I’d like to know if that’s a proper fix. Please advise :)

**Comment by jlaine** [comment]
Ouch that's a good catch. I'd have to re-read that block of code, as there are some intricacies involved here..
