### ISSUE TITLE
Path validation abandon

### ISSUE THREAD

**Issue by francescobarbarulo** [aiortc/aioquic#208]
Hi! I am working on a scenario that makes use of the path validation. I have the HTTP server running on a remote host and the HTTP client running on my laptop, which is connected to the internet via WiFi. Server and client are the ones provided in the _examples_ directory. I made a little modification to the _http3\_client.py_: I made the client performing 10 HTTP requests to the _padding_ endpoint within the same QUIC connection, so that I can simulate a handover in between two consecutive requests.
Once the handover is done, I expect the server to initiate path validation upon the reception of a non-probing frame from the new client address. The server promotes the new address as primary path and sends the path challenge frame to the client. Now, what happens if either the path challenge or the path response frame is lost?
RFC 9000 specifies that "Endpoints SHOULD abandon path validation based on a timer". Is this implemented in the current version of aioquic? Because it seems that if one of the two frames is lost, the endpoint abandons immediately the path validation procedure. Is this right?

**Comment by louisaber** [comment]
hello @francescobarbarulo 
i have the same problem, did you find a solution?
