### ISSUE TITLE
HTTP/3 header validation

### ISSUE THREAD

**Issue by pgjones** [aiortc/aioquic#21]
I think aioquic should validate any headers it sends are valid (according to HTTP/3), for example you can currently send an empty `:path` header whereas RFC 7540 (HTTP/2 which I think applies here) states 

> This pseudo-header field MUST NOT be empty for "http" or "https"
      URIs; "http" or "https" URIs that do not contain a path component
      MUST include a value of '/'.

**Comment by jlaine** [comment]
Hi Philipe! I'd like to keep things as similar to H2Connection as possible, so : does H2Connection perform the equivalent validation or is it up to API consumers?

**Comment by pgjones** [comment]
[Yep](https://github.com/python-hyper/hyper-h2/blob/master/h2/utilities.py#L490)

**Comment by jlaine** [comment]
Then validate we must :)

**Comment by jlaine** [comment]
FYI, a first round of *incoming* header validation has landed in 7922c052c7dd313a96c33f21faeb1359ab591312
