### ISSUE TITLE
Streaming STDOUT from Popen()

### ISSUE THREAD

**Issue by guest271314** [aiortc/aioquic#226]
In JavaScript I have

```
var url = 'https://localhost:4433/tts';
var transport = new WebTransport(url);
transport.ready.then(async() => {
  var sender = await transport.createUnidirectionalStream();
  console.log(sender);
  var writer = sender.getWriter();
  var textEncoder = new TextEncoder('utf-8');
  var inputData = textEncoder.encode(`parec -d alsa_output.pci-0000_00_14.2.analog-stereo.monitor`);
  await writer.write(inputData);
  await writer.close();
  await writer.closed;
  var readable = await transport.incomingUnidirectionalStreams;
  readable.pipeTo(
    new WritableStream({
        write(v) {
           v.pipeTo(new WritableStream({
               write(data) {
                   console.log(data);
               }, close() {
                   console.log('close 1');
               }
           }))
        }, close() {
            console.log('close 0');
        }
    })
  );
});
```

In Python I have (using GoogleChrome samples code)

```
input_data = b''

# CounterHandler implements a really simple protocol:
#   - For every incoming bidirectional stream, it counts bytes it receives on
#     that stream until the stream is closed, and then replies with that byte
#     count on the same stream.
#   - For every incoming unidirectional stream, it counts bytes it receives on
#     that stream until the stream is closed, and then replies with that byte
#     count on a new unidirectional stream.
#   - For every incoming datagram, it sends a datagram with the length of
#     datagram that was just received.
class CounterHandler:

    def __init__(self, session_id, http: H3Connection) -> None:
        self._session_id = session_id
        self._http = http
        self._counters = defaultdict(int)

    def h3_event_received(self, event: H3Event) -> None:
        if isinstance(event, DatagramReceived):
            payload = str(len(event.data)).encode('ascii')
            self._http.send_datagram(self._session_id, payload)

        if isinstance(event, WebTransportStreamDataReceived):
            print('event', event)
            if event.data:
                print('event.data', event.data)
                global input_data
                input_data = event.data
                self._counters[event.stream_id] += len(event.data)
            if event.stream_ended:
                print('event.stream_ended', event.stream_ended)
                if stream_is_unidirectional(event.stream_id):
                    response_id = self._http.create_webtransport_stream(
                        self._session_id, is_unidirectional=True)
                else:
                    response_id = event.stream_id
                '''
                data = subprocess.run(split(input_data.decode()), stdout=subprocess.PIPE)           
                payload = data.stdout
                self._http._quic.send_stream_data(
                    response_id, payload, end_stream=True)
                '''
                process = subprocess.Popen(split(input_data.decode()), stdout=subprocess.PIPE)
                os.set_blocking(process.stdout.fileno(), False)
                for chunk in iter(lambda: process.stdout.read(1024*1024), b''):
                    if chunk is not None:
                        # print(chunk)
                        self._http._quic.send_stream_data(
                            response_id, chunk, end_stream=False)
                        # break
                self.stream_closed(event.stream_id)

    def stream_closed(self, stream_id: int) -> None:
        try:
            print('stream_closed')
            del self._counters[stream_id]
        except KeyError:
            pass
```

At `console`

```
Uint8Array(756) ...
close 1
```
If I set 

```end_stream=False``

and do not include the 

```break```

 in Python I get a 

```'Connection lost.'``` 

error in JavaScript.

What is the pattern necessary and how to re-arrange the Python code to continue sending the chunks from `iter(lambda: process.stdout.read(1024*1024), b'')` to client?

**Comment by guest271314** [comment]
@yutakahirano Both the code in this repository and at GooglChrome/samples/webtransport throws 

```
Uncaught (in promise) WebTransportError: Opening handshake failed.
```

If you folks have working code in WPT can you kindly update the code in this repository and GoogleChrome/samples to avoid the above error (and make sure `WebTransport` examples work as intended)?

**Comment by guest271314** [comment]
@jlaine GoogleChrome/samples updated their `webtransport_server.py` code and the corresponding JavaScript https://github.com/GoogleChrome/samples/pull/749.

Launch Chromium (currently testing on Chromium 97.0.4682.0 (Developer Build) (64-bit)
Revision 220e1d1cc8b376ddb84bd6dfcc4812563e246429-refs/heads/main@{#934701}) or Chrome with 

```
--ignore-certificate-errors-spki-list="MYAm6JUV9241ZPRovWdEvo7UlgCVfQLzDPDsjlCyYEk="
```

update client.js at line 134 to

```
let reader = stream.readable.pipeThrough(decoder).getReader();
```

to avoid 

```
Uncaught (in promise) TypeError: stream.pipeThrough is not a function
    at readFromIncomingStream
```

error because stream is `WebTransportBidirectionalStream {readable: ReadableStream, writable: WritableStream}` not a `ReadableStream` itself, 
on a Linux machine with PulseAudio installed (substitute any user defined stream) to get name of monitor device

```
$ pactl list | grep -A2 'Source #' | grep 'Name: .*\.monitor$' | cut -d" " -f
```

update `webtransport_server.py` lines 139-152

```
if isinstance(event, WebTransportStreamDataReceived):
            if event.data != b'':
                # use result of pactl here
                cmd = 'parec', '-d', 'alsa_output.pci-0000_00_14.2.analog-stereo.monitor'
                process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
                os.set_blocking(process.stdout.fileno(), False)
                for c in iter(lambda: process.stdout.read(512), b''): 
                    if c is not None:                     
                        self._http._quic.send_stream_data(
                            event.stream_id, c, end_stream=False)
                        print(c)
```
then load client.html at `file:` protocol (for an unknown reason https://localhost:4433/client.html does not load on Chromium 97), select `"Open a bidirectional stream"` option, connect, then observe 

1) Bytes object will be printed at terminal
2) The stream will not be read at the browser tab
3) The browser tab will crash

**Comment by guest271314** [comment]
![Screenshot_2021-11-01_19-33-17](https://user-images.githubusercontent.com/4174848/139777934-c9ee2eab-49a4-4f10-947d-b382cfff62f6.png)

**Comment by guest271314** [comment]
An alternative for streaming captured audio device which currently crashes the browser 100% of the time

```
        if isinstance(event, WebTransportStreamDataReceived):
            if event.data != b'':
                for c in iter(lambda: ''.join(choice(digits) for i in range(512)).encode('ascii'), b''):  # replace '' with b'' for Python 3
                    if c is not None:
                        self._http._quic.send_stream_data(
                            event.stream_id, c, end_stream=False)                        
                        print(c)
```
[webtransport_server.py.zip](https://github.com/aiortc/aioquic/files/7457726/webtransport_server.py.zip)

**Comment by jlaine** [comment]
I'm sorry but I'm going to have to ask you to make a more efficient use of the issue tracker, posting a stream of blobs of code and comments isn't likely to lead to progress. A quick look at the comments posted here talks about at least 3 different things:

- supposed incompatibilities between aioquic and the WebTransport specs
- something about your custom code running blocking external processes using subprocess.Popen (this is a red flag - mixing asyncio code with something that holds up the event loop)
- a crash in a browser (way outside my scope)

If you have identified an issue please provide the minimal diff against the code in `main` and steps to reproduce this one issue.

**Comment by guest271314** [comment]
@jlaine I have encountered this problem before. Individuals tend to not actually read and test the code I post, instead attempt to characterize me or focus on me, not the code itself.

The title of the issues should be self-evident to you: We cannot stream using your code. `aioquic`, for reasons uniknown to me, never sends data to the browser when  a loop is used to read/write data.

I even supplied code in the last post that is not `Popen()` to demonstrate `aioquic` is broken. If you actually run the code and try to stream random data to the browser using `aioquic` you will not be successful.

Read the tittle of the issue: You cannot stream STDOUT to the browser using your `aioquic` code with `WebTransport`. That is a glaring issue I am not sure how you missed - unless you still have not actually run the code. It is trivial to reproduce and crashes the browser 100% of the time.

> - something about your custom code running blocking external processes using subprocess.Popen (this is a red flag - mixing asyncio code with something that holds up the event loop)
> - a crash in a browser (way outside my scope)

I can stream using PHP without any issues. I can stream using Python and Native Messaging. Trying to use `aioquic` to stream has not been successful, yet.

I am not inventing the fact using your code

1) auiquic never sending data to the browser using `Popen()` or `iter(lambda)`
2) Crashes the browser 100% of the time

Complete code to reproduce: https://gist.github.com/guest271314/5f567517f94572e84026e76ec6e7cd89.

Launch Chrome with `--origin-to-force-quic-on=localhost:4433 --ignore-certificate-errors-spki-list=MYAm6JUV9241ZPRovWdEvo7UlgCVfQLzDPDsjlCyYEk=`

`python3 webtransport_server.py certificate.pem certificate.key`

I am not impressed with WebTransport so far. A lot of server code that just does not work, changes ever week or so. I can just do this with PHP with data streaming to browser and no crashes:

```
<?php
  header('Vary: Origin');
  header("Access-Control-Allow-Origin: *");
  header("Access-Control-Allow-Methods: POST");
  header("Content-Type: text/plain");
  header("X-Powered-By:");
  $input = fopen("php://input", "rb");
  stream_set_blocking($input, 0);
  echo passthru(stream_get_contents($input));
  fclose($input);
  exit(0);
?>
(await fetch('http://localhost:8001', {body:'command'<ReabaleStream|text>})).body

```

**Comment by yutakahirano** [comment]
I think this is not related to aioquic. This is to be resolved at https://crbug.com/1266662 (and https://github.com/GoogleChrome/samples/pull/749#issuecomment-957080738).

@guest271314, I want to ask you to report issues to the right place.

**Comment by guest271314** [comment]
@yutakahirano 

> I think this is not related to aioquic. 

How do you know that?

aioquic has not worked in at least weeks. GoogleChrome/sample has not worked either. You folks have not settled down on a stable API, yet, so it is rather difficult to determine if aioquic is the issue or Chromium source code, you are moving the target every few days. `WebTransport` did not stream before @bashi updated the GoogleChrome/samples code. Your WPT tests are too trivial to be significant, passing minimal bytes both ways - you do not really test until it breaks, I do.

> @guest271314, I want to ask you to report issues to the right place.

Well, some of you Chromium authors cannot handle constructive feedback, don't really want to know when your code is broken, or at least don;t want me to tell you your code is broken, directly, with tests to support the claims, yet without rancor, so someone in your organzation banned me from filing Chromium bugs https://github.com/guest271314/banned/issues/5. Will not make the bugs I report magically go away, but that is the case nonetheless. Are you sure your colleagues can handle being told their code is broken?

**Comment by guest271314** [comment]
@yutakahirano I tried the code again after updates to Chromium source code and GoogleChrome/samples.

No crash. 

Data is printed to terminal.

The data still never reaches the client from WebTransport server.

```
Error while reading datagrams: WebTransportError: Connection lost.
Error while accepting streams: WebTransportError: Connection lost.
Connection closed abruptly.
Error while reading from stream #1: WebTransportError: Connection lost.
```

**Comment by yutakahirano** [comment]
That sounds like a bug in GoogleChrome/samples or Chrome. Let's discuss bugs on the right places.

**Comment by guest271314** [comment]
@yutakahirano I have no idea where the bug is. From perspective here the bug is in aioquic. How did you exclude aioquic from being the source of the bug?

**Comment by yutakahirano** [comment]
> @yutakahirano I have no idea where the bug is. From perspective here the bug is in aioquic. How did you exclude aioquic from being the source of the bug?

I'm not excluding the possibility, but I recommend you to start with GoogleChrome/samples for now, because:

1. People in GoogleChrome/samples (bashi, yutakahirano) are somewhat more eager to help you.
2. @jlaine will need more succinct reproduction (for example, reproduction without GoogleChrome/samples) to investigate the issue from the aioquic point of view.

If it turns out to be an aioquic bug, then we can open another issue in this repository, with a more succinct reproduction.

**Comment by guest271314** [comment]
@yutakahirano https://github.com/GoogleChrome/samples/issues/756
