### ISSUE TITLE
 it seems that the client send Connection close before receiving the http body of style.css?

### ISSUE THREAD

**Issue by saying-yan** [aiortc/aioquic#236]
I test the example file `http3_server.py` and `http3_client.py`, got the output for client: 
```
2021-11-01 20:49:15,672 INFO quic [217781c05f7c65da] ALPN negotiated protocol h3
2021-11-01 20:49:15,673 INFO client New session ticket received
2021-11-01 20:49:15,681 INFO client Response received for GET / : 1276 bytes in 0.007 s (1.424 Mbps)
2021-11-01 20:49:15,681 INFO client Push received for GET /style.css : 0 bytes
2021-11-01 20:49:15,681 INFO quic [217781c05f7c65da] Connection close sent (code 0x0, reason )
```

Got the `style.css`, but it is `0 bytes`.
Analysing with Wireshark, it seems that the client send `Connection close` before receiving the http body of `style.css`?

**Comment by jlaine** [comment]
You are right, the demo client does not wait for push requests to complete before returning, they are treated as a bonus.

**Comment by shortstorie** [comment]
Hello. Sorry if my question will be stupid, but is it possible to modify the demo client to wait for the whole body of the requested file? I'm trying to use this in Quic Network Simulator as the 2 endpoints. I can't quite figure it out, how or where could I extend the code to receive the whole body of the http request. Is there documentation on it somewhere that I can get ideas from? Is it complicated to do for someone not so familiar with the source code? Thanks for the reply in advance!

**Comment by jlaine** [comment]
The client *does* wait for the body of the *requested* file. What it does not wait for is additional (unrequested) files pushed by the server.
