### ISSUE TITLE
ERR_METHOD_NOT_SUPPORTED, Opening handshake failed.

### ISSUE THREAD

**Issue by guest271314** [aiortc/aioquic#237]
At terminal

```
2021-11-13 11:39:45,945 INFO quic [4654232e7292bb80] ALPN negotiated protocol h3
2021-11-13 11:39:45,947 INFO quic [4654232e7292bb80] Connection close sent (code 0x109, reason ENABLE_WEBTRANSPORT requires H3_DATAGRAM)
```

At browser

```
Failed to establish a connection to https://quic.aiortc.org/wt: net::ERR_METHOD_NOT_SUPPORTED.
VM23:11 Opening handshake failed.
(anonymous) @ VM23:11
Promise.catch (async)
(anonymous) @ VM23:10
quic.aiortc.org/:1 Uncaught (in promise) WebTransportError: Opening handshake failed.
```

Steps to reeproduce:

Follow instructions at examples/README for Chromium.

Potentially related https://github.com/GoogleChrome/samples/pull/749#issuecomment-961623180, https://github.com/GoogleChrome/samples/pull/754/commits/b83dc66a8f24e357201c6dd0e8aed26d26ba5ea0.

**Comment by jlaine** [comment]
Not enough information about what you are doing here. What's your server, what's your client?

**Comment by guest271314** [comment]
Running the examples in this repository on Chromium.

**Comment by jlaine** [comment]
I'm not a Chromium maintainer. Either you help me pinpoint a problem specifically in the code I wrote or I suggest you look elsewhere for help.

**Comment by guest271314** [comment]
What happens when you run the WebTransport example code of Chronmium/Chrome? Do you get a handshake error?

**Comment by guest271314** [comment]
> Not enough information about what you are doing here. What's your server, what's your client?

Following instructions at https://github.com/aiortc/aioquic/tree/main/examples on Chromium 99.0.4802.0 (Developer Build) (64-bit)

```
$ python3 examples/http3_server.py --certificate tests/ssl_cert.pem --private-key tests/ssl_key.pem
2022-01-02 04:44:28,758 INFO quic [c9e1a9847a619c4e] ALPN negotiated protocol h3
2022-01-02 04:44:28,761 INFO quic [c9e1a9847a619c4e] HTTP request CONNECT /wt
2022-01-02 04:44:28,764 INFO quic [c9e1a9847a619c4e] Stream 0 reset by peer (error code 268, final size 127)
```

```
let transport = new WebTransport('https://localhost:4433/wt');
await transport.ready;

let stream = await transport.createBidirectionalStream();
let reader = stream.readable.getReader();
let writer = stream.writable.getWriter()

await writer.write(new Uint8Array([65, 66, 67]));
let received = await reader.read();
await transport.close();

console.log('received', received);
Failed to establish a connection to https://localhost:4433/wt: net::ERR_METHOD_NOT_SUPPORTED.
Uncaught WebTransportError: Opening handshake failed.
tab.html:1 Uncaught (in promise) WebTransportError: Opening handshake failed.

```

**Comment by BruceChai-SM** [comment]
@guest271314 Have you got the way to fix this error? I am currently having this same problem. Thanks!

**Comment by guest271314** [comment]
@BruceChai-SM I have not found a fix.

**Comment by Niek** [comment]
Same issue here, related comment I saw in the Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1011392#c107

**Comment by guest271314** [comment]
@Niek The relevant parties do not appear to be interested in fixing the issue. My goal experimenting with `WebTransport` was for live-streaming media https://github.com/aiortc/aioquic/issues/242. That does not appear to be possible using either GoogleChrome/samples code or aioquic.

**Comment by Niek** [comment]
@guest271314 I found a working code sample here:
https://github.com/GoogleChrome/samples/blob/gh-pages/webtransport/webtransport_server.py

It's strange that WebTransport requires such a specific HTTP/3 server setup.

**Comment by guest271314** [comment]
@Niek Yes, that code runs, though does not support live-streaming. I also do not gather why Chromium authors who updated `WebTransport` in GoogleChrome/samples did not update code in the main dependency. I mentioned this handshake error in a PR there.

**Comment by BruceChai-SM** [comment]
> @guest271314 I found a working code sample here:
> 
> https://github.com/GoogleChrome/samples/blob/gh-pages/webtransport/webtransport_server.py
> 
> 
> 
> It's strange that WebTransport requires such a specific HTTP/3 server setup.

👍Yeah, I also found this example works today.

**Comment by BruceChai-SM** [comment]
> @Niek Yes, that code runs, though does not support live-streaming. I also do not gather why Chromium authors who updated `WebTransport` in GoogleChrome/samples did not update code in the main dependency. I mentioned this handshake error in a PR there. 

Thanks, @guest271314 Can you share the link to the PR please?

**Comment by guest271314** [comment]
@BruceChai-SM Works in general, yes, using the code published, except for the unmerged PR that fixes reading bidirectional stream https://github.com/GoogleChrome/samples/pull/752. I have not achieved the requirement of live-streaming media https://github.com/GoogleChrome/samples/issues/756. The stream and datagram eventual grow in internal buffer size (should not be buffered at all), and stops streaming. 

> Can you share the link to the PR please?

https://github.com/GoogleChrome/samples/pull/749
