### ISSUE TITLE
Server does not receive all the data sent on different streams from the client 

### ISSUE THREAD

**Issue by wrizzhi** [aiortc/aioquic#238]
I implemented a simple client -server using aioquic and I am trying to send the data through different streams using 
get_next_available_stream_id() function. 

For example, if I have 10 items to send each of size 5KB the client will create 10 streams and send each item on a separate stream. The server also knows that 10 streams were created and gets the data from them, However, when I increase the size of the items to more than 50KB, the server does not acknowledge the creation of more than 3 streams and only items from the first two streams are received. 

If anyone can comment on what is happening it would be helpful. I am adding the github repo for reference 
[https://github.com/wrizzhi/quic_client_server](url)

**Comment by wrizzhi** [comment]
attaching screenshots of the client and server output:

client output:
![clint_out](https://user-images.githubusercontent.com/53214794/142009876-fcec859c-5dcd-4c87-8233-1669bdbf6d20.JPG)

The client creates 10 different streams, however, the server acks only 2. 

Server output:
![server_out](https://user-images.githubusercontent.com/53214794/142010102-79e706fd-3d3d-4c9b-a1b1-59781f4a8e62.JPG)

**Comment by jlaine** [comment]
I'm sorry but I just don't have the time to review third-pary code..
