### ISSUE TITLE
Http3 Client Example fails on POST Data

### ISSUE THREAD

**Issue by GenerelSchwerz** [aiortc/aioquic#241]
When testing the http3_client.py example with these parameters: 
```python3 test.py -k -q "output" -d "hi"  https://quic.aiortc.org/httpbin/anything```

The code fails to send any data, with the returned output being: 
```python
b'{"args":{},"data":"","files":{},"form":{},"headers":{"Content-Type":"application/x-www-form-urlencoded","Host":"quic.aiortc.org","User-Agent":"aioquic/0.9.17"},"json":null,"method":"POST","origin":"::ffff:144.129.0.146","url":"https://quic.aiortc.org/httpbin/anything"}\n'
```

(The output above was found by adding an additional line at 271, printing http_event.data)

Here is a full qlog for debugging: 
``
{"qlog_format": "JSON", "qlog_version": "0.3", "traces": [{"common_fields": {"ODCID": "d77a36f69d04d039"}, "events": [{"data": {"new": "control", "stream_id": 2}, "name": "http:stream_type_set", "time": 1637888029084.1213}, {"data": {"new": "qpack_encoder", "stream_id": 6}, "name": "http:stream_type_set", "time": 1637888029084.164}, {"data": {"new": "qpack_decoder", "stream_id": 10}, "name": "http:stream_type_set", "time": 1637888029084.1758}, {"data": {"owner": "local", "max_idle_timeout": 60000, "initial_max_data": 1048576, "initial_max_stream_data_bidi_local": 1048576, "initial_max_stream_data_bidi_remote": 1048576, "initial_max_stream_data_uni": 1048576, "initial_max_streams_bidi": 128, "initial_max_streams_uni": 128, "ack_delay_exponent": 3, "max_ack_delay": 25, "disable_active_migration": false, "active_connection_id_limit": 8, "initial_source_connection_id": "0b1f091967bb4295"}, "name": "transport:parameters_set", "time": 1637888029084.2515}, {"data": {"key_type": "server_initial_secret", "trigger": "tls"}, "name": "security:key_updated", "time": 1637888029084.5764}, {"data": {"key_type": "client_initial_secret", "trigger": "tls"}, "name": "security:key_updated", "time": 1637888029084.6814}, {"data": {"bytes_in_flight": 1280, "cwnd": 12800}, "name": "recovery:metrics_updated", "time": 1637888029085.6206}, {"data": {"frames": [{"frame_type": "crypto", "length": 383, "offset": 0}, {"frame_type": "padding"}], "header": {"packet_number": 0, "packet_type": "initial", "scid": "0b1f091967bb4295", "dcid": "d77a36f69d04d039"}, "raw": {"length": 1280}}, "name": "transport:packet_sent", "time": 1637888029085.6262}, {"data": {"count": 1, "raw": [{"length": 1288, "payload_length": 1280}]}, "name": "transport:datagrams_sent", "time": 1637888029085.6277}, {"data": {"type": "initial", "packet_number": 0}, "name": "recovery:packet_lost", "time": 1637888029286.1367}, {"data": {"bytes_in_flight": 1280, "cwnd": 12800}, "name": "recovery:metrics_updated", "time": 1637888029286.1511}, {"data": {"bytes_in_flight": 0, "cwnd": 6400, "ssthresh": 6400}, "name": "recovery:metrics_updated", "time": 1637888029286.2466}, {"data": {"bytes_in_flight": 1280, "cwnd": 6400, "ssthresh": 6400}, "name": "recovery:metrics_updated", "time": 1637888029286.7205}, {"data": {"frames": [{"frame_type": "crypto", "length": 383, "offset": 0}, {"frame_type": "padding"}], "header": {"packet_number": 1, "packet_type": "initial", "scid": "0b1f091967bb4295", "dcid": "d77a36f69d04d039"}, "raw": {"length": 1280}}, "name": "transport:packet_sent", "time": 1637888029286.7527}, {"data": {"count": 1, "raw": [{"length": 1288, "payload_length": 1280}]}, "name": "transport:datagrams_sent", "time": 1637888029286.7705}, {"data": {"count": 1, "raw": [{"length": 1288, "payload_length": 1280}]}, "name": "transport:datagrams_received", "time": 1637888029289.8132}, {"data": {"frames": [{"ack_delay": 4.0, "acked_ranges": [[0, 0]], "frame_type": "ack"}, {"frame_type": "crypto", "length": 123, "offset": 0}], "header": {"packet_number": 0, "packet_type": "initial", "dcid": "0b1f091967bb4295", "scid": "5b9780115c9b4914"}, "raw": {"length": 177}}, "name": "transport:packet_received", "time": 1637888029290.0364}, {"data": {"key_type": "server_handshake_secret", "trigger": "tls"}, "name": "security:key_updated", "time": 1637888029292.3313}, {"data": {"frames": [{"frame_type": "crypto", "length": 1056, "offset": 0}], "header": {"packet_number": 1, "packet_type": "handshake", "dcid": "0b1f091967bb4295", "scid": "5b9780115c9b4914"}, "raw": {"length": 1103}}, "name": "transport:packet_received", "time": 1637888029292.578}, {"data": {"key_type": "client_handshake_secret", "trigger": "tls"}, "name": "security:key_updated", "time": 1637888029293.4395}, {"data": {"owner": "remote", "original_destination_connection_id": "d77a36f69d04d039", "max_idle_timeout": 60000, "stateless_reset_token": "2ad22182d4c969df40f7a23770f4d774", "initial_max_data": 1048576, "initial_max_stream_data_bidi_local": 1048576, "initial_max_stream_data_bidi_remote": 1048576, "initial_max_stream_data_uni": 1048576, "initial_max_streams_bidi": 128, "initial_max_streams_uni": 128, "ack_delay_exponent": 3, "max_ack_delay": 25, "disable_active_migration": false, "active_connection_id_limit": 8, "initial_source_connection_id": "5b9780115c9b4914", "max_datagram_frame_size": 65536}, "name": "transport:parameters_set", "time": 1637888029293.6477}, {"data": {"frames": [{"ack_delay": 4.000000000814907, "acked_ranges": [[0, 0]], "frame_type": "ack"}], "header": {"packet_number": 2, "packet_type": "initial", "scid": "0b1f091967bb4295", "dcid": "5b9780115c9b4914"}, "raw": {"length": 50}}, "name": "transport:packet_sent", "time": 1637888029294.1467}, {"data": {"frames": [{"ack_delay": 4.000000000814907, "acked_ranges": [[1, 1]], "frame_type": "ack"}], "header": {"packet_number": 3, "packet_type": "handshake", "scid": "0b1f091967bb4295", "dcid": "5b9780115c9b4914"}, "raw": {"length": 49}}, "name": "transport:packet_sent", "time": 1637888029294.167}, {"data": {"key_type": "server_initial_secret", "trigger": "tls"}, "name": "security:key_retired", "time": 1637888029294.2043}, {"data": {"key_type": "client_initial_secret", "trigger": "tls"}, "name": "security:key_retired", "time": 1637888029294.2134}, {"data": {"bytes_in_flight": 0, "cwnd": 6400, "ssthresh": 6400}, "name": "recovery:metrics_updated", "time": 1637888029294.2427}, {"data": {"count": 1, "raw": [{"length": 107, "payload_length": 99}]}, "name": "transport:datagrams_sent", "time": 1637888029294.257}, {"data": {"count": 1, "raw": [{"length": 1288, "payload_length": 1280}]}, "name": "transport:datagrams_received", "time": 1637888029294.4922}, {"data": {"frames": [{"frame_type": "crypto", "length": 1232, "offset": 1056}], "header": {"packet_number": 2, "packet_type": "handshake", "dcid": "0b1f091967bb4295", "scid": "5b9780115c9b4914"}, "raw": {"length": 1280}}, "name": "transport:packet_received", "time": 1637888029294.6506}, {"data": {"frames": [{"ack_delay": 0.999999996565748, "acked_ranges": [[1, 2]], "frame_type": "ack"}], "header": {"packet_number": 4, "packet_type": "handshake", "scid": "0b1f091967bb4295", "dcid": "5b9780115c9b4914"}, "raw": {"length": 49}}, "name": "transport:packet_sent", "time": 1637888029295.016}, {"data": {"count": 1, "raw": [{"length": 57, "payload_length": 49}]}, "name": "transport:datagrams_sent", "time": 1637888029295.0312}, {"data": {"count": 1, "raw": [{"length": 1288, "payload_length": 1280}]}, "name": "transport:datagrams_received", "time": 1637888029295.1516}, {"data": {"frames": [{"frame_type": "crypto", "length": 1232, "offset": 2288}], "header": {"packet_number": 3, "packet_type": "handshake", "dcid": "0b1f091967bb4295", "scid": "5b9780115c9b4914"}, "raw": {"length": 1280}}, "name": "transport:packet_received", "time": 1637888029295.2544}, {"data": {"frames": [{"ack_delay": 0.0, "acked_ranges": [[1, 3]], "frame_type": "ack"}], "header": {"packet_number": 5, "packet_type": "handshake", "scid": "0b1f091967bb4295", "dcid": "5b9780115c9b4914"}, "raw": {"length": 48}}, "name": "transport:packet_sent", "time": 1637888029295.6077}, {"data": {"count": 1, "raw": [{"length": 56, "payload_length": 48}]}, "name": "transport:datagrams_sent", "time": 1637888029295.64}, {"data": {"count": 1, "raw": [{"length": 1192, "payload_length": 1184}]}, "name": "transport:datagrams_received", "time": 1637888029425.5745}, {"data": {"trigger": "key_unavailable"}, "name": "transport:packet_dropped", "time": 1637888029425.656}, {"data": {"frames": [{"frame_type": "crypto", "length": 935, "offset": 3520}], "header": {"packet_number": 5, "packet_type": "handshake", "dcid": "0b1f091967bb4295", "scid": "5b9780115c9b4914"}, "raw": {"length": 983}}, "name": "transport:packet_received", "time": 1637888029425.709}, {"data": {"key_type": "server_1rtt_secret", "trigger": "tls"}, "name": "security:key_updated", "time": 1637888029426.295}, {"data": {"key_type": "client_1rtt_secret", "trigger": "tls"}, "name": "security:key_updated", "time": 1637888029426.4504}, {"data": {"frames": [{"frame_type": "crypto", "length": 89, "offset": 0}, {"fin": false, "frame_type": "stream", "length": 18, "offset": 0, "stream_id": 3}, {"fin": false, "frame_type": "stream", "length": 1, "offset": 0, "stream_id": 7}, {"fin": false, "frame_type": "stream", "length": 1, "offset": 0, "stream_id": 11}], "header": {"packet_number": 6, "packet_type": "1RTT", "dcid": "0b1f091967bb4295", "scid": ""}, "raw": {"length": 152}}, "name": "transport:packet_received", "time": 1637888029426.6306}, {"data": {"state": true}, "name": "connectivity:spin_bit_updated", "time": 1637888029426.6338}, {"data": {"new": "control", "stream_id": 3}, "name": "http:stream_type_set", "time": 1637888029426.9453}, {"data": {"new": "qpack_encoder", "stream_id": 7}, "name": "http:stream_type_set", "time": 1637888029426.974}, {"data": {"new": "qpack_decoder", "stream_id": 11}, "name": "http:stream_type_set", "time": 1637888029427.0042}, {"data": {"bytes_in_flight": 107, "cwnd": 6400, "ssthresh": 6400}, "name": "recovery:metrics_updated", "time": 1637888029427.2832}, {"data": {"frames": [{"ack_delay": 0.999999996565748, "acked_ranges": [[1, 3], [5, 5]], "frame_type": "ack"}, {"frame_type": "crypto", "length": 52, "offset": 0}], "header": {"packet_number": 6, "packet_type": "handshake", "scid": "0b1f091967bb4295", "dcid": "5b9780115c9b4914"}, "raw": {"length": 107}}, "name": "transport:packet_sent", "time": 1637888029427.288}, {"data": {"bytes_in_flight": 366, "cwnd": 6400, "ssthresh": 6400}, "name": "recovery:metrics_updated", "time": 1637888029427.2905}, {"data": {"frames": [{"ack_delay": 0.999999996565748, "acked_ranges": [[6, 6]], "frame_type": "ack"}, {"connection_id": "cb4858330123fcbf", "frame_type": "new_connection_id", "length": 8, "reset_token": "d4ee2d7782f70249cb0633fc1e180d8b", "retire_prior_to": 0, "sequence_number": 1}, {"connection_id": "0cffcb48a05a7b3d", "frame_type": "new_connection_id", "length": 8, "reset_token": "9d7464e9368a3f8a36c17cf1a5ce4966", "retire_prior_to": 0, "sequence_number": 2}, {"connection_id": "a8d773b43a705845", "frame_type": "new_connection_id", "length": 8, "reset_token": "7abb3fcb5e6c097f22a8f30e3b6f9d7e", "retire_prior_to": 0, "sequence_number": 3}, {"connection_id": "378c96d34e84691a", "frame_type": "new_connection_id", "length": 8, "reset_token": "b0662d1f3ebfc212003d48ce5626c28d", "retire_prior_to": 0, "sequence_number": 4}, {"connection_id": "66afe3eec42a129e", "frame_type": "new_connection_id", "length": 8, "reset_token": "babea3293b9241e027c101e24aaaf3f9", "retire_prior_to": 0, "sequence_number": 5}, {"connection_id": "de38db6481d031e7", "frame_type": "new_connection_id", "length": 8, "reset_token": "3af8292bd16074400842fd9e054fe4fc", "retire_prior_to": 0, "sequence_number": 6}, {"connection_id": "0f209343d32ebef0", "frame_type": "new_connection_id", "length": 8, "reset_token": "beb328b48d477936e9757d661e43219f", "retire_prior_to": 0, "sequence_number": 7}, {"fin": false, "frame_type": "stream", "length": 13, "offset": 0, "stream_id": 2}, {"fin": false, "frame_type": "stream", "length": 4, "offset": 0, "stream_id": 6}, {"fin": false, "frame_type": "stream", "length": 1, "offset": 0, "stream_id": 10}], "header": {"packet_number": 7, "packet_type": "1RTT", "scid": "", "dcid": "5b9780115c9b4914"}, "raw": {"length": 259}}, "name": "transport:packet_sent", "time": 1637888029427.2927}, {"data": {"count": 1, "raw": [{"length": 374, "payload_length": 366}]}, "name": "transport:datagrams_sent", "time": 1637888029427.296}, {"data": {"frame": {"frame_type": "headers", "headers": [{"name": ":method", "value": "POST"}, {"name": ":scheme", "value": "https"}, {"name": ":authority", "value": "quic.aiortc.org"}, {"name": ":path", "value": "/httpbin/anything"}, {"name": "user-agent", "value": "aioquic/0.9.17"}, {"name": "content-type", "value": "application/x-www-form-urlencoded"}]}, "length": 46, "stream_id": 0}, "name": "http:frame_created", "time": 1637888029427.4873}, {"data": {"frame": {"frame_type": "data"}, "length": 2, "stream_id": 0}, "name": "http:frame_created", "time": 1637888029427.5098}, {"data": {"bytes_in_flight": 449, "cwnd": 6400, "ssthresh": 6400}, "name": "recovery:metrics_updated", "time": 1637888029427.629}, {"data": {"frames": [{"fin": true, "frame_type": "stream", "length": 52, "offset": 0, "stream_id": 0}], "header": {"packet_number": 8, "packet_type": "1RTT", "scid": "", "dcid": "5b9780115c9b4914"}, "raw": {"length": 83}}, "name": "transport:packet_sent", "time": 1637888029427.633}, {"data": {"count": 1, "raw": [{"length": 91, "payload_length": 83}]}, "name": "transport:datagrams_sent", "time": 1637888029427.635}, {"data": {"count": 1, "raw": [{"length": 246, "payload_length": 238}]}, "name": "transport:datagrams_received", "time": 1637888029553.795}, {"data": {"frames": [{"ack_delay": 2.0, "acked_ranges": [[7, 7]], "frame_type": "ack"}, {"frame_type": "handshake_done"}, {"connection_id": "c460437939f10243", "frame_type": "new_connection_id", "length": 8, "reset_token": "11af380daf741c2a381d909dadd2d5f2", "retire_prior_to": 0, "sequence_number": 1}, {"connection_id": "622106a1073c603f", "frame_type": "new_connection_id", "length": 8, "reset_token": "3b66fefe895e1af135014cc9916d561a", "retire_prior_to": 0, "sequence_number": 2}, {"connection_id": "80fa634eac5d6603", "frame_type": "new_connection_id", "length": 8, "reset_token": "2289998a7c6bce17b7439584eb0ce9c0", "retire_prior_to": 0, "sequence_number": 3}, {"connection_id": "d2d6b3db57b90908", "frame_type": "new_connection_id", "length": 8, "reset_token": "0abe4614415188581bc04fe9eb00bbe0", "retire_prior_to": 0, "sequence_number": 4}, {"connection_id": "fcad158aeda31c85", "frame_type": "new_connection_id", "length": 8, "reset_token": "600d1d976ff60465f02bba6e12f15c81", "retire_prior_to": 0, "sequence_number": 5}, {"connection_id": "1b23f7029f8a3644", "frame_type": "new_connection_id", "length": 8, "reset_token": "8e8aa7aa9ab4042ef06968004001c0d5", "retire_prior_to": 0, "sequence_number": 6}, {"connection_id": "2b1ab1a48fe40cca", "frame_type": "new_connection_id", "length": 8, "reset_token": "9325ddae6388beebfa8986925371b2e5", "retire_prior_to": 0, "sequence_number": 7}, {"fin": false, "frame_type": "stream", "length": 3, "offset": 1, "stream_id": 7}], "header": {"packet_number": 7, "packet_type": "1RTT", "dcid": "0b1f091967bb4295", "scid": ""}, "raw": {"length": 238}}, "name": "transport:packet_received", "time": 1637888029553.8496}, {"data": {"state": false}, "name": "connectivity:spin_bit_updated", "time": 1637888029553.8538}, {"data": {"bytes_in_flight": 190, "cwnd": 6400, "ssthresh": 6400, "latest_rtt": 127.00000000040745, "min_rtt": 127.00000000040745, "smoothed_rtt": 127.00000000040745, "rtt_variance": 63.50000000020373}, "name": "recovery:metrics_updated", "time": 1637888029553.9275}, {"data": {"key_type": "server_handshake_secret", "trigger": "tls"}, "name": "security:key_retired", "time": 1637888029553.9456}, {"data": {"key_type": "client_handshake_secret", "trigger": "tls"}, "name": "security:key_retired", "time": 1637888029553.9482}, {"data": {"bytes_in_flight": 83, "cwnd": 6400, "ssthresh": 6400}, "name": "recovery:metrics_updated", "time": 1637888029553.9565}, {"data": {"count": 1, "raw": [{"length": 41, "payload_length": 33}]}, "name": "transport:datagrams_received", "time": 1637888029555.1843}, {"data": {"frames": [{"ack_delay": 0.992, "acked_ranges": [[7, 8]], "frame_type": "ack"}], "header": {"packet_number": 8, "packet_type": "1RTT", "dcid": "0b1f091967bb4295", "scid": ""}, "raw": {"length": 33}}, "name": "transport:packet_received", "time": 1637888029555.21}, {"data": {"state": false}, "name": "connectivity:spin_bit_updated", "time": 1637888029555.2126}, {"data": {"bytes_in_flight": 0, "cwnd": 6400, "ssthresh": 6400, "latest_rtt": 127.00000000040745, "min_rtt": 127.00000000040745, "smoothed_rtt": 127.00000000040745, "rtt_variance": 47.625000000152795}, "name": "recovery:metrics_updated", "time": 1637888029555.2454}, {"data": {"frames": [{"ack_delay": 0.0, "acked_ranges": [[7, 8]], "frame_type": "ack"}], "header": {"packet_number": 9, "packet_type": "1RTT", "scid": "", "dcid": "5b9780115c9b4914"}, "raw": {"length": 32}}, "name": "transport:packet_sent", "time": 1637888029555.326}, {"data": {"count": 1, "raw": [{"length": 40, "payload_length": 32}]}, "name": "transport:datagrams_sent", "time": 1637888029555.328}, {"data": {"count": 1, "raw": [{"length": 93, "payload_length": 85}]}, "name": "transport:datagrams_received", "time": 1637888029557.5403}, {"data": {"frames": [{"fin": false, "frame_type": "stream", "length": 54, "offset": 0, "stream_id": 0}], "header": {"packet_number": 9, "packet_type": "1RTT", "dcid": "0b1f091967bb4295", "scid": ""}, "raw": {"length": 85}}, "name": "transport:packet_received", "time": 1637888029557.5647}, {"data": {"state": false}, "name": "connectivity:spin_bit_updated", "time": 1637888029557.5671}, {"data": {"frame": {"frame_type": "headers", "headers": [{"name": ":status", "value": "200"}, {"name": "server", "value": "aioquic/0.9.17"}, {"name": "date", "value": "Fri, 26 Nov 2021 00:53:49 GMT"}, {"name": "content-type", "value": "application/json"}, {"name": "content-length", "value": "270"}, {"name": "access-control-allow-origin", "value": "*"}, {"name": "access-control-allow-credentials", "value": "true"}]}, "length": 52, "stream_id": 0}, "name": "http:frame_parsed", "time": 1637888029557.6516}, {"data": {"count": 1, "raw": [{"length": 313, "payload_length": 305}]}, "name": "transport:datagrams_received", "time": 1637888029557.7043}, {"data": {"frames": [{"fin": false, "frame_type": "stream", "length": 273, "offset": 54, "stream_id": 0}], "header": {"packet_number": 10, "packet_type": "1RTT", "dcid": "0b1f091967bb4295", "scid": ""}, "raw": {"length": 305}}, "name": "transport:packet_received", "time": 1637888029557.7249}, {"data": {"state": false}, "name": "connectivity:spin_bit_updated", "time": 1637888029557.7275}, {"data": {"frame": {"frame_type": "data"}, "length": 270, "stream_id": 0}, "name": "http:frame_parsed", "time": 1637888029557.7502}, {"data": {"frames": [{"ack_delay": 1.0000000038417056, "acked_ranges": [[7, 10]], "frame_type": "ack"}], "header": {"packet_number": 10, "packet_type": "1RTT", "scid": "", "dcid": "5b9780115c9b4914"}, "raw": {"length": 33}}, "name": "transport:packet_sent", "time": 1637888029558.9673}, {"data": {"count": 1, "raw": [{"length": 41, "payload_length": 33}]}, "name": "transport:datagrams_sent", "time": 1637888029558.9724}, {"data": {"count": 1, "raw": [{"length": 43, "payload_length": 35}]}, "name": "transport:datagrams_received", "time": 1637888029569.3062}, {"data": {"frames": [{"fin": true, "frame_type": "stream", "length": 2, "offset": 327, "stream_id": 0}], "header": {"packet_number": 11, "packet_type": "1RTT", "dcid": "0b1f091967bb4295", "scid": ""}, "raw": {"length": 35}}, "name": "transport:packet_received", "time": 1637888029569.3306}, {"data": {"state": false}, "name": "connectivity:spin_bit_updated", "time": 1637888029569.3333}, {"data": {"frame": {"frame_type": "data"}, "length": 0, "stream_id": 0}, "name": "http:frame_parsed", "time": 1637888029569.36}, {"data": {"frames": [{"ack_delay": 1.0000000038417056, "acked_ranges": [[7, 11]], "frame_type": "ack"}], "header": {"packet_number": 11, "packet_type": "1RTT", "scid": "", "dcid": "5b9780115c9b4914"}, "raw": {"length": 33}}, "name": "transport:packet_sent", "time": 1637888029569.6028}, {"data": {"count": 1, "raw": [{"length": 41, "payload_length": 33}]}, "name": "transport:datagrams_sent", "time": 1637888029569.605}, {"data": {"frames": [{"error_code": 0, "error_space": "application", "frame_type": "connection_close", "raw_error_code": 0, "reason": ""}], "header": {"packet_number": 12, "packet_type": "1RTT", "scid": "", "dcid": "5b9780115c9b4914"}, "raw": {"length": 30}}, "name": "transport:packet_sent", "time": 1637888029569.735}, {"data": {"count": 1, "raw": [{"length": 38, "payload_length": 30}]}, "name": "transport:datagrams_sent", "time": 1637888029569.7373}, {"data": {"key_type": "server_1rtt_secret", "trigger": "tls"}, "name": "security:key_retired", "time": 1637888030598.733}, {"data": {"key_type": "client_1rtt_secret", "trigger": "tls"}, "name": "security:key_retired", "time": 1637888030598.7393}, {"data": {"bytes_in_flight": 0, "cwnd": 6400, "ssthresh": 6400}, "name": "recovery:metrics_updated", "time": 1637888030598.755}], "vantage_point": {"name": "aioquic", "type": "client"}}]}
``

**Comment by jlaine** [comment]
I've digged into this and it looks like:

- the HTTP/3 client does send the data
- the HTTP/3 server does receive the data
- the data is then correctly passed to the ASGI layer
- the data is then correctly passed to the WSGI layer
- httpbin does not receive the data!
