### ISSUE TITLE
Multiple HeadersReceived events in a single stream

### ISSUE THREAD

**Issue by ahopkins** [aiortc/aioquic#246]
The [example server code here](https://github.com/aiortc/aioquic/blob/645dd009af08f8723a44db1d22028b75358b6176/examples/http3_server.py#L329) seems to imply that the `HeadersReceived` event might be triggered multiple times:

```python
        if isinstance(event, HeadersReceived) and event.stream_id not in self._handlers:
        ...
        elif (
            isinstance(event, (DataReceived, HeadersReceived))
            and event.stream_id in self._handlers
        ):
        ...
```

If that is the case, then it would seem that on subsequent events there would be a need to append headers. However, this does not seem like it is allowed if my understanding is correct:

> An HTTP message (request or response) consists of:
>   1. the header section, sent as a single HEADERS frame (see Section 7.2.2),

[Source](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-4.1-4)

Clarity on this would be much appreciated.

**Comment by jlaine** [comment]
The HTTP/3 code validates that we receive receive a single HEADERS, then DATA then maybe HEADERS (trailers). This is enforced by checking `stream.headers_recv_state`:

https://github.com/aiortc/aioquic/blob/645dd009af08f8723a44db1d22028b75358b6176/src/aioquic/h3/connection.py#L611
https://github.com/aiortc/aioquic/blob/645dd009af08f8723a44db1d22028b75358b6176/src/aioquic/h3/connection.py#L625

=> the example client and server are assured that what is passed to their `http_event_received` is valid in the current state, unless you have found a case I missed?

Here are our tests:
https://github.com/aiortc/aioquic/blob/645dd009af08f8723a44db1d22028b75358b6176/tests/test_h3.py#L543

**Comment by ahopkins** [comment]
Thanks @jlaine. I guess it was just not obvious to me that this event was also for trailers. I have no additional missing edge case.

**Comment by jlaine** [comment]
Thanks for challenging the code though, at least now there's an explanation available :)
