### ISSUE TITLE
OSError: [Errno 97] Address family not supported by protocol

### ISSUE THREAD

**Issue by Hasan-Aga** [aiortc/aioquic#249]
I am trying to run the first example on the Mininet VM (Ubuntu 20.04), but, where I run `python examples/http3_server.py --certificate tests/ssl_cert.pem --private-key tests/ssl_key.pem` i get:
`Traceback (most recent call last):
  File "examples/http3_server.py", line 572, in <module>
    loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mininet/master/aioquic/src/aioquic/asyncio/server.py", line 204, in serve
    _, protocol = await loop.create_datagram_endpoint(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1306, in create_datagram_endpoint
    sock = socket.socket(
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
`

The application works fine on my host machine, is there any particular reason why this does not run on the VM?

PS, I printed the `family` variable which is causing the problem and it gave me this:
```
AddressFamily.AF_UNIX
AddressFamily.AF_UNIX
AddressFamily.AF_INET6
AddressFamily.AF_INET6
```
I am guessing that this issue is related to IPv6.
It seems that IPv6 is disabled by default on the Mininet VM, but why is that a problem?

**Comment by jlaine** [comment]
It's a problem because .. we're in 2022?

But more seriously having to test and maintain multiple code paths for this edge case is a pain, most platforms have dual stacks.

**Comment by Hasan-Aga** [comment]
I eventually solved this problem by ditching the stock Mininet VM and started over with a stock Ubuntu VM, the problem is with Mininet VM.
