### ISSUE TITLE
How to generate ssl_cert.pem  ssl_key.pem  pycacert.pem

### ISSUE THREAD

**Issue by xtuyaowu** [aiortc/aioquic#267]
hi：
   How to generate ssl_cert.pem  ssl_key.pem  pycacert.pem ？for
   python examples/http3_server.py --certificate tests/ssl_cert.pem --private-key tests/ssl_key.pem
   python examples/http3_client.py --ca-certs tests/pycacert.pem wss://localhost:4433/ws

thanks！

**Comment by jlaine** [comment]
These files are just dummy certificates for tests, you should be using a valid certificate for your own usage.

**Comment by ahopkins** [comment]
I'd suggest mkcert. It's a simple tool, and you can set the certificates up with a local authority so they are trusted.

https://mkcert.org/
