### ISSUE TITLE
Mac installation error

### ISSUE THREAD

**Issue by fareedlb** [aiortc/aioquic#276]
I am having issues with the installation of aioquic on an m1 based Mac. I am getting this error

**src/aioquic/_crypto.c:4:10: fatal error: 'openssl/err.h' file not found
    #include <openssl/err.h>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1
    [end of output]**

**Comment by jlaine** [comment]
See the README, you need to install openssl development files

**Comment by fareedlb** [comment]
> 
Thank your your kind reply. I have installed openssl and still getting the same error

**Comment by jonnythebard** [comment]
If the `export` in the document didn't work you can run `brew info openssl` to see what to export.
in my case, `brew info openssl` instructed me to export the like below.
```
export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include
```
And it solved the problem.
