### ISSUE TITLE
Connect AIOQUIC using Browser without passing the flag origin-to-force-quic-on

### ISSUE THREAD

**Issue by abnv418** [aiortc/aioquic#286]
Hello,

I find that I can connect my chrome browser to https://quic.aiortc.org/ without using the flag "--origin-to-force-quic-on". and the protocol used is HTTP/3.  But when I try to connect the chrome browser with the aioquic server locally on my machine without the flag "--origin-to-force-quic-on" it fails to connect with the error "ERR_CONNECTION_REFUSED". I was successful in generating valid certificates for local host using mkcert and I do not need to pass the flag "--ignore-certificate-errors-spki-list" anymore.

Now I don't want to use the flag "--origin-to-force-quic-on" with the chrome,  is it possible to run ?

I also would like to know how is your hosted server working without any flag ? and it also works with other browser like Firefox and Safari.

**Comment by rmarx** [comment]
Hey @abnv418,

Could you give a little bit more information on your local setup specifically?

You say "I was successful in generating valid certificates for local host using mkcert and I do not need to pass the flag "--ignore-certificate-errors-spki-list" anymore", but as far as I know, that's... impossible? How exactly did you generate those certs (can you give the mkcert command so I can try to reproduce?)

Are you 100% sure your local setup with the mkcert localhost certificate works if you **DO** pass `--origin-to-force-quic-on` but **DO NOT** pass `--ignore-certificate-errors-spki-list`? How do you test this?

If that does work but without the `--origin-to-force-quic-on` flag it does not, you should probably collect a netlog (explained here: https://www.chromium.org/for-testers/providing-network-details/) and upload it here so we can get some more details on what's going wrong...

Finally, are you sure you're doing alt-svc correctly with an HTTP/1 or HTTP/2 server at TCP port 443 so chrome can properly discover the QUIC server at UDP? I'm not sure how to interpret your last sentence `it also works with other browser like Firefox and Safari` (does it mean your setup works with FF/safari, or are you asking how the hosted server works with them?)

**Comment by jlaine** [comment]
quic.aiortc.org is running:

- the unmodified demo aioquic HTTP/3 server directly to serve HTTP/3
- nginx (which does SSL termination + adds the Alt-Svc header) + uvicorn to serve HTTP/1 and HTTP/2

Both these setups run the unmodified demo.py ASGI application.
