### ISSUE TITLE
CFFI support

### ISSUE THREAD

**Issue by DemiMarie** [aiortc/aioquic#287]
This is to improve performance on PyPy.

**Comment by jlaine** [comment]
I don't understand this issue could you elaborate please?

**Comment by DemiMarie** [comment]
> I don't understand this issue could you elaborate please?

PyPy uses a different internal representation of Python objects than CPython does.  For this and other reasons, its implementation of the CPython C API uses an emulation layer, which is rather slow.  CFFI, on the other hand, is very fast on PyPy due to dedicated code in PyPy’s JIT compiler.  It’s also pretty fast on CPython.

**Comment by jlaine** [comment]
OK so no I have no plans to implement this myself. I'd be happy to review a PR though, provided there are benchmarks for both CPython and PyPy so we can make an informed decision.
