### ISSUE TITLE
why current version use WindowsSelectorEventLoopPolicy in tests/utils.py for python3.8 since its issue has already been fixed?

### ISSUE THREAD

**Issue by NewUserHa** [aiortc/aioquic#289]
https://github.com/aiortc/aioquic/blob/96ce66be6d125aa823f2945ce7b924a9adce4304/tests/utils.py#L94-L104

why current version use WindowsSelectorEventLoopPolicy in tests/utils.py for python3.8 since its issue has already been fixed?
original python issue: https://bugs.python.org/issue39148
new python issue: https://github.com/python/cpython/issues/83329
fixed in: https://github.com/python/cpython/pull/20169
and I verified that Python 3.8.10 is shipped with that fix.

related PR: https://github.com/aiortc/aioquic/pull/280

**Comment by jlaine** [comment]
Right, thanks for pointing this out. I've adjusted the test suite in PR #292 which *only* removes the useless workaround.

@msoxzw you're going to want to rebase PR #280 once this is merged.
