### ISSUE TITLE
Is there any options to request self-signed certificate but not verify it?

### ISSUE THREAD

**Issue by gogopro-dev** [aiortc/aioquic#296]
I got stuck at point of getting information from server about self-signed certificate. Because with verify mode ssl.CERT_NONE, server doesn't send certificate for client, and with any others i receive Error: 298, reason: self-signed certificate, frame_type: 6. And i didn't found option to configure ssl.verify_flags. Will be glad to receive any useful information.

**Comment by jlaine** [comment]
I don't understand the question: ssl.CERT_NONE specifies that an aioquic-based *client* should not verify the *server* certificate.  It has no impact on what a server does.
