### ISSUE TITLE
Creating smaller DCIDs

### ISSUE THREAD

**Issue by mzealey** [aiortc/aioquic#319]
In RFC9000 it says the initial DCID must be at least 8 bytes, but I believe after this it can be reduced even to 0. Is it possible to add a `QuicConfiguration` option like `initial_connection_id_length=8` and then allow `connection_id_length` to be configured independently of this? This can serve to reduce bandwidth for services which do not need connection migration or for other reasons.

**Comment by jlaine** [comment]
Can you please elaborate on what you want to achieve here?
