### ISSUE TITLE
Packet stream stops until PING frame is not sent.

### ISSUE THREAD

**Issue by mdakram28** [aiortc/aioquic#323]
I am trying to run aioquic server and it looks like for some streams, the sending stream stops for several seconds and then a PING frame is sent and the last packet is sent only after that PING frame is acked. Here's an example of the issue:

| Time | Frames | Payload |
| --- | --- | --- |
| 23.139 | ACK | Protected Payload (KP0), DCID=f3e35e8c656d7e06, PKN: 1595, ACK |
| 23.181 | STREAM | Protected Payload (KP0), DCID=bd2bb779fa02e47c, PKN: 1713, STREAM(80) |
| 23.181 | ACK | Protected Payload (KP0), DCID=f3e35e8c656d7e06, PKN: 1596, ACK |
| 23.223 | STREAM | Protected Payload (KP0), DCID=bd2bb779fa02e47c, PKN: 1714, STREAM(80) |
| 23.225 | ACK | Protected Payload (KP0), DCID=f3e35e8c656d7e06, PKN: 1597, ACK |
| 23.265 | STREAM | Protected Payload (KP0), DCID=bd2bb779fa02e47c, PKN: 1715, STREAM(80) |
| 23.268 | ACK | Protected Payload (KP0), DCID=f3e35e8c656d7e06, PKN: 1598, ACK |
| | | ... long delay ... |
| 29.659 | PING,PADDING | Protected Payload (KP0), DCID=bd2bb779fa02e47c, PKN: 1718, **PING**, PADDING  <-- After 6.391s |
| 29.659 | ACK | Protected Payload (KP0), DCID=f3e35e8c656d7e06, PKN: 1599, ACK |
| 29.735 | STREAM | Protected Payload (KP0), DCID=bd2bb779fa02e47c, PKN: 1719, STREAM(80), DATA <-- Last Frame |
| 29.735 | ACK,PING | Protected Payload (KP0), DCID=f3e35e8c656d7e06, PKN: 1600, ACK, PING |

I am using the aioquic client.

**Comment by pyfisch** [comment]
Not a contributor, just following aioquic. You can enable QLOGs on both the server and the client and then visualize the connection with [qvis](https://qvis.quictools.info/#/files). There are multiple reasons why a packet stream could stop, e.g. lost ACKs, flow control, a connection change. If you share the QLOGs I will have a look what might be the reason.
