### ISSUE TITLE
UDP datagrams containing Initial packets have UDP payloads of less than 1200 bytes

### ISSUE THREAD

**Issue by consen** [aiortc/aioquic#325]
RFC 9000:

> Clients MUST ensure that UDP datagrams containing Initial packets have UDP payloads of at least 1200 bytes, adding PADDING frames as necessary. A client that sends padded datagrams allows the server to send more data prior to completing address validation.

However, aioquic client send QUIC Initial packet，UDP payloads less than 1200 bytes:
![image](https://user-images.githubusercontent.com/2787272/187024177-1f56b9d2-9358-432c-a16d-ce3b7870924e.png)

**Comment by jlaine** [comment]
The relevant code is here:

https://github.com/aiortc/aioquic/blob/c758b4d936b95347b46cc697da8d9823a3b059cc/src/aioquic/quic/packet_builder.py#L272-L280

**Comment by consen** [comment]
> The relevant code is here:
> 
> https://github.com/aiortc/aioquic/blob/c758b4d936b95347b46cc697da8d9823a3b059cc/src/aioquic/quic/packet_builder.py#L272-L280

yes, it is caused by condition `self._packet._is_ackeliciting`.
