### ISSUE TITLE
WebTransport support

### ISSUE THREAD

**Issue by rsepassi** [aiortc/aioquic#331]
Hi, is WebTransport supported, or is there a plan to do so? Or does it not belong in aioquic? Keen to use it in Python and trying to figure out if it's already there or on the roadmap or what the right building blocks would be to impl if needed.

**Comment by pyfisch** [comment]
https://github.com/aiortc/aioquic/tree/main/examples#webtransport

**Comment by rsepassi** [comment]
Amazing, thank you.
