### ISSUE TITLE
Datagram Size

### ISSUE THREAD

**Issue by msoxzw** [aiortc/aioquic#339]
https://github.com/aiortc/aioquic/blob/444be09157aed3c81881d18647484165dd07139c/src/aioquic/quic/packet_builder.py#L20

https://www.rfc-editor.org/rfc/rfc9000.html#name-datagram-size

Both client and server must expand the payload of all UDP datagrams carrying Initial packets to at least the smallest allowed maximum datagram size of 1200 bytes. Thereafter, any maximum datagram size larger than 1200 bytes can be discovered using Path Maximum Transmission Unit Discovery or Datagram Packetization Layer PMTU Discovery.

**Comment by jlaine** [comment]
Sure, do you plan to work on a PR?

**Comment by jlaine** [comment]
This is fixed in the current code
