### ISSUE TITLE
How to retrieve server TLS certificate？

### ISSUE THREAD

**Issue by byron-li** [aiortc/aioquic#357]
Hi,
I'm interested in retrieving the TLS certificate from the QUIC server side. 
Are there any ways to achieve this? similar to the result of the getpeercert() method in the SSLSocket class.

**Comment by jlaine** [comment]
Currently we don't expose an API for this, could you give me an idea of the usecase?

**Comment by GalaxySnail** [comment]
It is useful for downloading ceritificates via QUIC. Recently, curl got a `curl -w "%{certs}"` option, see: https://daniel.haxx.se/blog/2022/12/28/curl-w-certs/.
