### ISSUE TITLE
Find a replacement for deprecated `ssl.match_hostname`

### ISSUE THREAD

**Issue by jlaine** [aiortc/aioquic#368]
When connecting to a server, we rely on the standard library's [ssl.matchhostname](https://docs.python.org/3/library/ssl.html#ssl.match_hostname) method to check the certificate presented by the server is valid for the hostname we connected to. Howver this method has been deprecated since Python 3.7 so we need to find a suitable replacement.

So far I have found:

- urllib3 [vendors this method](https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/ssl_match_hostname.py ) into its code.  This does seem like a great option as it puts the burden of maintaining a critical piece of code on us.
- OpenSSL has an [X509_check_host](https://www.openssl.org/docs/man1.1.1/man3/X509_check_host.html) method. AFAICT this is not accessible from pyOpenSSL.

**Comment by GalaxySnail** [comment]
I found [service-identity](https://github.com/pyca/service-identity) which is mentioned in [trio's documentation](https://trio.readthedocs.io/en/latest/reference-io.html#datagram-tls-support), it may be helpful.

**Comment by jlaine** [comment]
> I found [service-identity](https://github.com/pyca/service-identity) which is mentioned in [trio's documentation](https://trio.readthedocs.io/en/latest/reference-io.html#datagram-tls-support), it may be helpful.

Thank you *very much*, this looks like exactly what we want!
