### ISSUE TITLE
Aioquic server does not close the connection when client sends packets with unexpected frame type.

### ISSUE THREAD

**Issue by QUICTester** [aiortc/aioquic#406]
Hi,

During our tests involving Aioquic (https://github.com/aiortc/aioquic/commit/239f99b8a3d4f5bc88cb280df765f35722cefe57) implementation, we identified a protocol violation in the server implementation.

Aioquic server processes Handshake packet carrying an unexpected frame type.
You can reproduce this behaviour by:

1) Sending a Initial packet carrying a Client Hello message.
2) Sending a Handshake packet carrying a frame with type (0xFF).

According to (Section 17.2.4, RFC 9000), endpoints MUST treat receipt of Handshake packets with other frames as a connection error of type PROTOCOL_VIOLATION. Violations of the protocol lead to an immediate close.

Please let me know if you require any additional information.
Thank you for your time.

**Comment by jlaine** [comment]
Indeed, point taken.

**Comment by jlaine** [comment]
I've looked into this and don't understand the testing methodology. Scripts and / or captures of the exchange would be welcome.

I've re-read the code, and AFAICT aioquic *does* reject any unknown frame types or frame types not expected at a given epoch with a protocol violation, so I'd like to be able to reproduce the issue.

**Comment by QUICTester** [comment]
Hi, here is a pcap file and aioquic sever's secret log. Look at the 13th packet in captureAioquic.pcap

[captureAndSecret.zip](https://github.com/aiortc/aioquic/files/13294078/captureAndSecret.zip)

**Comment by jlaine** [comment]
I can see the 0xFF frame but I'm not sure how this proves the server is misbehaving. Unless I'm mistaken by the time that packet is received, the handshake has been completed from the server's perspective and it will have discarded its HANDSHAKE keys. Most likely it is unable to decode your HANDSHAKE packet and is immediately dropping it.

**Comment by QUICTester** [comment]
In the pcap, sent earlier, the handshake is not confirmed yet. The client has not sent Client Finished to the server. This means that the server is not discarding its Handshake key yet. Look at the 14th packet, the server still sends a Handshake packet carrying a PING frame. 

There is an exception when Aioquic is processing the Handshake packet with 0xFF frame. Here is the server log.
[aioquic.log](https://github.com/aiortc/aioquic/files/13314070/aioquic.log)

**Comment by jlaine** [comment]
The "frame type" you are sending is not actually 0xFF, it's a malformed variable-length integer so it cannot even be decoded. This is actually visible in Wireshark, the dissector croaks on your packet.

The exception could be handled differently, but you are not so much testing how aioquic handles "unknown frame types" as how it handles garbage :)
