### ISSUE TITLE
Undocumented cryptography dependency

### ISSUE THREAD

**Issue by kpcyrd** [aiortc/aioquic#414]
I noticd in [aioquic/quic/packet.py](https://github.com/aiortc/aioquic/blob/main/src/aioquic/quic/packet.py) is this import

```python
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
```

Yet in pyproject.toml the `crypography` library is not listed as a dependency:

```toml

dependencies = [
    "certifi",
    "pylsqpack>=0.3.3,<0.4.0",
    "pyopenssl>=22",
    "service-identity>=23.1.0",
]
```

It seems the cryptgraphy dependency is fulfilled transitively, but should probably be listed explicitly.

**Comment by jlaine** [comment]
The dependency is fullfilled because pyopenssl depends on cryptography.  We can indeed make it explicit.
