### ISSUE TITLE
aioquic 0.9.22 dosent have your latest code changes and commits

### ISSUE THREAD

**Issue by Karthikdasari0423** [aiortc/aioquic#416]
Hi @jlaine 

aioquic 0.9.22 dosent have the latest code commits and changes

you have released aioquic 0.9.22 on Nov5 2023 as per https://pypi.org/project/aioquic/#history

and you have committed  this change https://github.com/aiortc/aioquic/commit/2ae1ad464294af5acc24d6582c1a9e680c0c5f0f by @ihlar on Nov 6 which have some aioquic library changes

Kindly request you to release a new aioquic 0.9.23 with latest code changes

**Comment by jlaine** [comment]
Uh yes, that's correct I don't push out a release after every commit.
