### ISSUE TITLE
Performance impact in the case of variable latency 

### ISSUE THREAD

**Issue by massvoice** [aiortc/aioquic#42]
Hi, 

I am currently testing aioquic in a simulation environment, where I have set a maximum bandwidth of 10 Mbps. 

In a normal scenario, I am able to achieve a throughput of around 9.2 Mbps, but when I implement variable delay in the packets using traffic control (variable delay 1ms to 10ms , uniform distribution), I observe a severe impact in the performance. (The maximum throughput achieve in this case in around 3 Mbps)

Please assist what might be the problem.

**Comment by jlaine** [comment]
You brought up what is possibly a legitimate issue, but no, I'm not going to do your homework for you. I am the sole maintainer of this package right now, so my resources are limited.

I'd be happy to review any suggestions for improvements one you analyze what is going on.

**Comment by massvoice** [comment]
Hi sure, I would be happy to analyze. Furthermore, I was not expecting you to do any homework for me. I thought, you being the sole maintainer and developer of the project, might already know about the problem or have some idea about it. 

Anyways, thank you for replying. Will update if I find something.

**Comment by jlaine** [comment]
Sorry for the cranky reply, it's a rough life maintaining opensource projects. I'd be happy to help out with the investigation once you have some data we can look at.
