### ISSUE TITLE
Why didn't I see QUIC packets when I was using wireshark

### ISSUE THREAD

**Issue by NotreDameDeParis** [aiortc/aioquic#43]
I am using the examples of aioquic respectively on the client and server.However,when i was using wireshark,I found that no quic packets can i receive.What i recieve are just UDP packets.However,I can get the info that shows  Congratulations, you loaded this page using HTTP/3!".Could you please tell me how this happens?

**Comment by SeaHOH** [comment]
If you are using Windows,  to capture packet on localhost, a loopback adapter is needed.

**Comment by NotreDameDeParis** [comment]
I am using Ubuntu(VMware),not windows.

**Comment by NotreDameDeParis** [comment]
I am using two Ubuntu virtual machines,one as a client and the other as a server.Then,I just used the example in aioquic and used wireshark.Unfortunately,I received no QUIC packets.

**Comment by NotreDameDeParis** [comment]
> If you are using Windows,  to capture packet on localhost, a loopback adapter is needed.
I am using two Ubuntu virtual machines,one as a client and the other as a server.Then,I just used the example in aioquic and used wireshark.Unfortunately,I received no QUIC packets.

**Comment by tianyaqu** [comment]
Virtual machine softwares like virtualbox will create a netwok interface in the host system,  you should capture on that interface.
To make it simple,  you can capture the packets on server side,  use the following command on the server shell, replace 'lo' with your listening interface and later analyse the quic.pcap file with wireshark, you will see all the quic packets.
`tcpdump -i lo port 4433 -w quic.pcap`

**Comment by NotreDameDeParis** [comment]
> Virtual machine softwares like virtualbox will create a netwok interface in the host system,  you should capture on that interface.
> To make it simple,  you can capture the packets on server side,  use the following command on the server shell, replace 'lo' with your listening interface and later analyse the quic.pcap file with wireshark, you will see all the quic packets.
> tcpdump -i lo port 4433 -w quic.pcap
