### ISSUE TITLE
Idle timeout should be a small value between local idle timeout and remote max idle timeout from transport parameters 

### ISSUE THREAD

**Issue by Shouhua** [aiortc/aioquic#466]
hi,
I read the doc about [idle timeout](https://datatracker.ietf.org/doc/html/rfc9000#name-idle-timeout) and found that idle timeout should be a small value between local and remote idle timeout.

_`Each endpoint advertises a max_idle_timeout, but the effective value at an endpoint is computed as the minimum of the two advertised values (or the sole advertised value, if only one endpoint advertises a non-zero value)`_

But our code just use the self._configration.idle_timeout: https://github.com/aiortc/aioquic/blob/74e8479e216f53df6d7625596f1b6d4a84477e84/src/aioquic/quic/connection.py#L1060
So is there anything I haven't considered about the code?

**Comment by rthalley** [comment]
Fixed, thanks for your report!
