### ISSUE TITLE
Add HTTP/2 Alt-Svc feature to HTTP3 Server/Client examples

### ISSUE THREAD

**Issue by Zhang-Junzhi** [aiortc/aioquic#473]
Add HTTP/2 Alt-Svc feature to HTTP3 Server/Client examples in order to help developers easily test and employ aioquic with normal UAs.
Please consider it.

**Comment by rthalley** [comment]
Do you mean that you want aioquic's example client to attempt HTTP/2 and process the Alt-Svc header?  If so, that's not really the right thing for aioquic.  I think what you want is better done inside of httpx when it eventually gets HTTP/3 support.

**Comment by Zhang-Junzhi** [comment]
> Do you mean that you want aioquic's example client to attempt HTTP/2 and process the Alt-Svc header? If so, that's not really the right thing for aioquic. I think what you want is better done inside of httpx when it eventually gets HTTP/3 support.

No. Sorry for not being clear.
I meant the server side (so that aioquic can be tested using normal browsers such as Chrome and Firefox), although I can figure it out by using an extra package such as aiohttp.
Feel free to close it anyway, if you don't think it's the right thing for aioquic.

**Comment by rthalley** [comment]
You can also look at Hypercorn for the server side, as I remember it doing Alt-Svc.  For Chrome-based browsers or Safari you can also publish an HTTPS record in the DNS.

**Comment by Zhang-Junzhi** [comment]
> You can also look at Hypercorn for the server side, as I remember it doing Alt-Svc. For Chrome-based browsers or Safari you can also publish an HTTPS record in the DNS.

Thanks for your information.

**Comment by rthalley** [comment]
One last thing, Chrome wants real TLS certs for HTTP/3, so if you use a self-signed cert and it doesn't work, that's why.
