### ISSUE TITLE
Sending images and other difficulties

### ISSUE THREAD

**Issue by AttilaDjerdj** [aiortc/aioquic#53]
Hello,
first of all thank you for your efforts and work. Im very interested in this project and quic (respectively http3) and would like to experiment a little bit, but i difficulties to continue. I have successfully installed the project and have been playing around with the examples. The http3_server is running and the http3_client can successfully communicate with the server.

As far as i understand the examples, the http3_server's response (by default) is determined by the demo.py file and the demo.py file specifies the index.html file to be send. By enabling the print-response option of the http3_client i can see, that the http3_server has send index.html file the http3_client and the content of the index.html file are printed in the terminal.

My difficulties begin here. Firstly, is it possible to open the index.html file, which was send from my http3_server to my http3_client, directly with a browser? For now, i can only see the respone in the terminal. Secondly, is there a possibility to send images together with html files?
My goal is to send webpages containing not only html text but also images.

Greetings,
Attila

**Comment by jlaine** [comment]
The demo server's web application is indeed in `demo.py`. There is nothing special about this demo, it is a standard ASGI application so you can replace it with your own, using any ASGI-compatible Python web framework, see https://asgi.readthedocs.io/en/latest/implementations.html

In terms of browser support, both Chrome Canary and Firefox nightly support HTTP/3 (I believe Firefox still has some issues at the moment), but they currently require manually enabling this support. There is some information on how to use Chrome here:

https://blog.cloudflare.com/http3-the-past-present-and-future/

**Comment by abnvsally** [comment]
@AttilaDjerdj 
Was it possible for you to send images or videos through the Web and open the index.html in chrome. ?
