### ISSUE TITLE
pip install -e . fail on mac.

### ISSUE THREAD

**Issue by CodeLife2012** [aiortc/aioquic#56]
```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 
-Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include 
-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
-I/Users/karl/.pyenv/versions/3.8.0/include/python3.8 
-c src/aioquic/_crypto.c 
-o build/temp.macosx-10.14-x86_64-3.8/src/aioquic/_crypto.o -std=c99

    src/aioquic/_crypto.c:4:10: fatal error: 'openssl/err.h' file not found
    #include <openssl/err.h>
             ^~~~~~~~~~~~~~~
    1 error generated.

    error: command 'clang' failed with exit status 1
```

Openssl is installed on `/usr/local/Cellar/openssl@1.1/1.1.1d` by brew.

**Comment by SalehAlawaji** [comment]
I faced the same issue. I solved it by creating symlinks, but I'm not sure if this the optimal solution for this issue. 
` ln -s /usr/local/opt/openssl/include/openssl /usr/local/include
ln -s /usr/local/opt/openssl/lib/libssl.1.1.dylib /usr/local/lib/`

**Comment by jlaine** [comment]
I encountered the same issue while setting up CI on GitHub Actions, the fix was:

```bash
export CFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib
```

**Comment by karanmankar95** [comment]
Hey I am facing the same problem but in windows. I installed Openssl in C:\OpenSSL-Win64. Any help would be appreciated.
![image](https://user-images.githubusercontent.com/61260957/91036562-32485100-e625-11ea-8d89-74dc038dfc60.png)

**Comment by EricPengShuai** [comment]
@karanmankar95 Same problem in windows. Have you solved it?

**Comment by mdakram28** [comment]
If you are using brew, try this:
```bash
# Install OpenSSL 3 if not installed
brew install openssl@3

export CFLAGS=-I$(brew --prefix openssl@3)/include
export LDFLAGS=-L$(brew --prefix openssl@3)/lib
```
Then run pip install

**Comment by mdebord-dlr** [comment]
> export CFLAGS=-I$(brew --prefix openssl@3)/include
> export LDFLAGS=-L$(brew --prefix openssl@3)/lib


Confirmed this fixed my issue on Mac OS (after trying many different things to solve this). Thanks!

**Comment by jlaine** [comment]
> export CFLAGS=-I$(brew --prefix openssl@3)/include
> export LDFLAGS=-L$(brew --prefix openssl@3)/lib

Do we need the explicit `@3` or does it work with `$(brew --prefix openssl)` ? I'm just curious because we are not doing `brew install openssl@3` so I'd like to keep things consistent.

**Comment by mdebord-dlr** [comment]
> > export CFLAGS=-I$(brew --prefix openssl@3)/include
> > export LDFLAGS=-L$(brew --prefix openssl@3)/lib
> 
> Do we need the explicit `@3` or does it work with `$(brew --prefix openssl)` ? I'm just curious because we are not doing `brew install openssl@3` so I'd like to keep things consistent.

It should work fine without it since brew will resolve the actual path. 
```
>> brew --prefix openssl
/opt/homebrew/opt/openssl@3
```
You could technically just put the actual path in there instead. The important part is that the actual path is correct for your system when setting the `CFLAGS` and `LDFLAGS` values.

**Comment by jlaine** [comment]
Thanks for the insights @mdakram28 and @mdebord-dlr, I am updating the README accordingly.
