### ISSUE TITLE
NAT traversal

### ISSUE THREAD

**Issue by keepsimple1** [aiortc/aioquic#57]
Is there a recommended way of using this lib in the context of NAT traversal (UDP)? For example, if I want to mix in a signaling protocol (or some keep-alive packets) with HTTP/3 QUIC and wanted to go through NAT, is there an existing way in this lib?

or, can we run one instance being both HTTP/3 server and a normal UDP client/endpoint (via the same port)? Thanks.

**Comment by jlaine** [comment]
First of all, apologies for not answering this ticket earlier.

I don't quite understand what your scenario is here. A QUIC server will be listening on a specific port, and that port is expected to be open. On the client side, NAT'ing should not be an issue since the client sends the first datagrams to the server, thereby punching a hole in the NAT.

Could you elaborate on what your situation is?

**Comment by keepsimple1** [comment]
Not a problem. Thanks for getting back. My case is that a client-initiated datagram will be dropped by the NAT router because it's a "unknown" peer.  To make the UDP punching work, the server has to send out UDP packet to the client as well (before QUIC connection established).   

This means that QUIC server will be able to send some non-QUIC packets while running.  Not to mention that the server also needs to send out some keep-alive packets to the port on NAT router open/active.

I've forked your repo and hacked with some patches. It's working for me now, and I'm not sure if some pieces can be refactored into a generic form and maybe even contribute back.

**Comment by mcopik** [comment]
@keepsimple1 Can you briefly describe your setup? Is it not sufficient to punch the hole in NAT, opening a specific port and letting QUIC use it?

Or is the problem caused by the keep-alive packets exchanged while QUIC server is listening?

**Comment by keepsimple1** [comment]
> Or is the problem caused by the keep-alive packets exchanged while QUIC server is listening?

yes, the problem was the keep-alive packets while QUIC server is listening. Now I've since solved the problem and using the same UDP port for both QUIC server and other client-side QUIC traffic by adding a demux at the socket. (My original custom keep-alive packets also worked but too ad-hoc).
