### ISSUE TITLE
HTTP/3 ASGI server?

### ISSUE THREAD

**Issue by keepsimple1** [aiortc/aioquic#59]
Is there a plan to implement a HTTP/3 ASGI server as part of this project? (something derives from the `http3_server.py` in `tests/` ?)

**Comment by sethmlarson** [comment]
Check out Hypercorn for an HTTP/3-ready server of ASGI apps: https://github.com/pgjones/hypercorn

**Comment by jlaine** [comment]
The `examples/http3_server.py` demo is an ASGI server by the way :)

As @sethmlarson pointed out if you want a more production-ready server, I'd go with hypercorn.

**Comment by keepsimple1** [comment]
Thank you.
