### ISSUE TITLE
Understanding packet header construction

### ISSUE THREAD

**Issue by massvoice** [aiortc/aioquic#6]
Hi, 

I am working on a project, which requires modifying packet headers, especially for the ack packets. 
Can you please help me understand the code flow via which I can modify the headers and add custom key values. 

Thanks.

**Comment by jlaine** [comment]
*Packet* headers are created using the `PacketBuilder` class, and parsed using `pull_quic_header`.

ACKs are frames, not packets, look at pull_ack_frame and push_ack_frame.

**Comment by massvoice** [comment]
Hi, thanks for the help. Even if ACKs are frames, I will be needing to modify the header of the frame to solve my purpose. Can you please let me know, how can I add a new key value pair in the header, and parse the same. It will be very helpful if you can give a sample on how can i add a custom value to the header and parse it when it is received at the server..  Thanks.
