### ISSUE TITLE
May the server send data proactively after the connection established between client and server?

### ISSUE THREAD

**Issue by lwmraymond** [aiortc/aioquic#66]
May the server send data proactively after the connection established between client and server?
I want to use the aioquic.asyncio.server and how to let server try to send data to the client proactively?
because server has to send hello message in some protocols, So should I just use the event to manage with or without data from a protocol to send by writer in handle_stream() with a loop or other methods?

I am looking forward to your reply!

**Comment by jlaine** [comment]
The stream API provided by `QuicConnectionProtocol` is pretty bad, I introduced it early on before I had a clear picture of what the API should look like. I am not satisfied with it, and will probably remove it in a future release, along with the `stream_handler` concept.

I think your best option is to subclass `QuicConnectionProtocol` as is done in the `examples/http3_server.py` example, and re-implement the `quic_event_received` method. This will allow you to handle the `HandshakeCompleted` event and send whatever data you wish.

I hope this helps!

**Comment by lwmraymond** [comment]
Thank you so much! I will follow your suggestion!
