### ISSUE TITLE
Certificate generation documentation?

### ISSUE THREAD

**Issue by pablogranolabar** [aiortc/aioquic#68]
Hi,

I am prototyping QUIC for a mobile application, thanks for making aioquic available.

Question: I am getting a certificate error even after hardcoding --host with the example http3 code, I am assuming that's because there is a mismatch between localhost and external server address I am communicating with (I'm not using localhost for development). Are there any documentation resources on how to generate the various certificates needed for that, if that is indeed the issue?

Here's the error:

```
2020-03-20 11:44:58,924 INFO quic [1dee7d339857a8fa] Connection close code 0x12A, reason hostname 'test.us-east-2.compute.amazonaws.com' doesn't match 'localhost'
```
Thanks in advance!

**Comment by jlaine** [comment]
There is nothing QUIC-specific about the certificates. You can use any certificate provider you would use for HTTPS, for instance letsencrypt
