### ISSUE TITLE
Issues connecting via Cronet -> demo:app

### ISSUE THREAD

**Issue by pablogranolabar** [aiortc/aioquic#70]
Hi!

Thanks again for your work on this project. I've been setting up a test environment here, to  experiment with Android + Cronet HTTP/3 libs for a mobile app.

I am simply using http3_server.py with the demo:app ASGI module, but cannot get Cronet to even negotiate a connection. Here is the error:
```
Exception in CronetUrlRequest: net::ERR_QUIC_PROTOCOL_ERROR, ErrorCode=10, InternalErrorCode=-356, Retryable=false, QuicDetailedErrorCode=25
```
Here's the relevant Cronet code:
```
private void callCronet() {
        CronetEngine.Builder myBuilder = new CronetEngine.Builder(this);
        cronetEngine = myBuilder
                .addQuicHint("quic.example.com", 8443, 8443)
                .enableHttpCache(CronetEngine.Builder.HTTP_CACHE_IN_MEMORY, 100 * 1024)
                .enableHttp2(true)
                .enableQuic(true)
                .build();

        Executor executor = Executors.newSingleThreadExecutor();
        UrlRequest.Callback callback = new MyUrlRequestCallback();
        UrlRequest.Builder builder = cronetEngine.newUrlRequestBuilder("https://quic.example.com:8443", callback, executor);
        UrlRequest urlRequest = builder.build();
        urlRequest.getStatus(new UrlRequest.StatusListener() {
            @Override
            public void onStatus(int status) {
                Log.e(TAG, status + " ");
            }
        });
        urlRequest.start();
    }

    private void callQuicCronet() {
        CronetEngine.Builder myBuilder = new CronetEngine.Builder(this);
        cronetEngine = myBuilder
                .enableHttpCache(CronetEngine.Builder.HTTP_CACHE_IN_MEMORY, 100 * 1024)
                .enableHttp2(true)
                .enableQuic(true)
                .addQuicHint("quic.tech", 8443, 8443)
                .build();

        Executor executor = Executors.newSingleThreadExecutor();
        UrlRequest.Callback callback = new MyUrlRequestCallback();
        UrlRequest.Builder builder = cronetEngine.newUrlRequestBuilder("https://quic.tech:8443", callback, executor);
        UrlRequest urlRequest = builder.build();
        urlRequest.getStatus(new UrlRequest.StatusListener() {
            @Override
            public void onStatus(int status) {
                Log.e(TAG, status + " ");
            }
        });
        urlRequest.start();
    }
```
We are able to connect without issue to the public QUIC endpoints above; for this local setup we have signed Let's Encrypt certs and are using the following command line to serve a one line index.html from examples/htdocs:
```
python3 examples/http3_server.py --certificate certs/fullchain1.pem --private-key certs/privkey1.pem --host quic.example.com --port 8443 -v -q quiclog "demo:app"
```
Any ideas?

Thanks in advance!

**Comment by jlaine** [comment]
I have zero experience with cronet, so I'm not going to be of much help regarding your custom code. Before going any further I suggest you try connecting to the following public servers using the same code:

https://bagder.github.io/HTTP3-test/

If the failure is truly specific to `aioquic` I'd be happy to look into it, otherwise I'd say the problem lies elsewhere.

**Comment by pablogranolabar** [comment]
Thanks jlaine, I'll try that next!

**Comment by pablogranolabar** [comment]
Ok, so with our current Cronet setup we've been able to successfully test each of these endpoints. I am sniffing traffic and see it coming in on the ingress side, but no response from aioquic in return. So there is no debugging information even showing up in http3_server.py verbose logging or the QUIC protocol logs themselves.

**Comment by pablogranolabar** [comment]
Hi again jlaine,

We still haven't been able to figure out this issue in connecting to aioquic, and our Cronet client connects without issue to all of the endpoints @ https://bagder.github.io/HTTP3-test/.

Any ideas? Is there a public endpoint for aioquic that we can test against as well, to try to figure out the issue?
Thanks in advance

**Comment by jlaine** [comment]
If you have tested all the endpoints in the linked page, you've already successfully tested two endpoints based on `aioquic`:

- `quic.aiortc.org` : this is purely the demo server provided in `examples/http3_server.py`

- `pgjones.dev`: this is `hypercorn` which relies on `aioquic` for HTTP/3 support

**Comment by pablogranolabar** [comment]
Thanks jlaine. Would it be possible to share the command line options / configuration for those endpoints?

**Comment by jlaine** [comment]
I can only speak for `quic.aiortc.org` which runs:

`python examples/http3_server.py --certificate demo/ssl_cert.pem --private-key demo/ssl_key.pem --port 443 --quic-log examples/htdocs/logs`

**Comment by VernonPerry** [comment]
Thanks jlaine. We've got a different approach for Android that I am exploring today, I will keep you posted with developments. Thanks for your help.

**Comment by david-stroup** [comment]
@VernonPerry hey! Did you remember how you solved it for Cronet? I probably experience the same issue.
Update: as I found, if self-signed certificate issued (private CA), then[ it is not possible for Cronet:](https://issues.chromium.org/issues/40138351)
> Agreed, we're not planning on allowing self-signed certificates with QUIC in Cronet, closing as WorksAsIntended.
