### ISSUE TITLE
Building compiled wheels for PyPI (Linux, Mac, Windows) 

### ISSUE THREAD

**Issue by honglei** [aiortc/aioquic#79]
Just like the same name topic: 
https://github.com/biopython/biopython/issues/1296

Maybe this method will help: https://pypi.org/project/cibuildwheel/

**Comment by jlaine** [comment]
Yes, this is the approach I've been working on in #78

**Comment by jlaine** [comment]
Update: wheel generation is working for Linux and Mac. Window still needs to be done, see #81

**Comment by jlaine** [comment]
The compiled wheels for all platforms are now on PyPI
