### ISSUE TITLE
building custorm Congestion Control policy on aioquic

### ISSUE THREAD

**Issue by honglei** [aiortc/aioquic#80]
Is there an example for demostrating how to use aioquic to implement  a customized Congestion Control policy like PCC Vivace/BBR/ Hybla?  It will be quite useful for college students to learn it.

https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#name-on-new-congestion-event
QPEP: A QUIC-Based Approach to Encrypted Performance Enhancing Proxies for High-Latency Satellite Broadband:
https://arxiv.org/abs/2002.05091
BBR:
https://github.com/google/bbr
PCC Vivace:
https://www.usenix.org/node/211246
https://github.com/KaiwenZha/PCC-Vivace

**Comment by jlaine** [comment]
Take a look at `recovery.py` you can easily replace the `QuicCongestionControl` class with your own. Once you have an implementation of BRR, please do submit a PR I'd be interested.
