### ISSUE TITLE
ImportError: /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: Undefined symbol "OPENSSL_no_config"

### ISSUE THREAD

**Issue by janev94** [aiortc/aioquic#86]
Hi, 

 Trying to run the aioquic H3 server on freeBSD 11.3 I get the error in the title of this issue. Seems like in openssl 1.1+ OPENSSL_no_config was replaced by OPENSSL_init.

Related libraries:
cffi==1.14.0
cryptography==2.9
six==1.14.0
wsproto==0.15.0

OS version:
FreeBSD 11.3-RELEASE

Openssl version:
OpenSSL 1.0.2s-freebsd  28 May 2019

Any ideas/help would be appreciated

**Comment by jlaine** [comment]
The error you point to originates in the `cryptography` module, I suggest you take it up there as there isn't anything I can do about it.

**Comment by janev94** [comment]
Correct, I've taken it theretoo  as soon as I posted this issue. Was a long shot, but I had hoped that you've seen this before and know a workaround. Anyway, will report back if there's any progress from the cryptography team in case someone else on freeBSD gets that in the future.
