### ISSUE TITLE
Unable to install in Ubuntu Linux (open error, 'encoding is an invalid keyword argument for this function'). 

### ISSUE THREAD

**Issue by SpencerDawkins** [aiortc/aioquic#88]
I'm using Ubuntu Linux under (1)  Windows Subsystem for Linux (WSL) on Windows 10 and (2) ChromeOS, and am seeing this error in both places. Please note that this traceback is from "pip install aioquic", so installing from files.pythonhosted.org, but when I clone the repository and "pip install -e .", I get what looks, to me, to be the same error. 

Perhaps I'm missing something obvious? 

spencer@sdawkins-NB0:/mnt/c/Users/sdawkins/Documents/Github/aioquic$ pip install aioquic                                Collecting aioquic                                                                                                        Using cached https://files.pythonhosted.org/packages/cb/de/e88c9ac83ec3f9caac691876fdc21233e9686887343b7bb815720efc0812/aioquic-0.8.7.tar.gz                                                                                                      Complete output from command python setup.py egg_info:                                                                  Traceback (most recent call last):                                                                                        File "<string>", line 1, in <module>                                                                                    File "/tmp/pip-build-zgfOZ9/aioquic/setup.py", line 10, in <module>                                                       with open(about_file, encoding="utf-8") as fp:                                                                      TypeError: 'encoding' is an invalid keyword argument for this function                                                                                                                                                                          ----------------------------------------                                                                            Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zgfOZ9/aioquic/

**Comment by jlaine** [comment]
That's very odd, what Python version are you running?

**Comment by SpencerDawkins** [comment]
@jlaine, thank you for the quick and accurate response. My system(s) were both set to default to python 2.7 (I suppose this is an Ubuntu thing). After making the appropriate changes, I'm now up and running with Python 3.7. 

You can definitely close this one.

**Comment by jlaine** [comment]
OK, thanks for letting me know!
