### ISSUE TITLE
how to run dos_x example?

### ISSUE THREAD

**Issue by ShuaiZhao** [aiortc/aioquic#90]
Hi, :)

would you be kind to provide examples about how to run dns over QUIC? 

Best,
SZ

**Comment by jlaine** [comment]
@tigertoes this one is for you ;)

**Comment by tigertoes** [comment]
Perhaps it would be best to include some instructions in the code itself? I can put a PR together.

**Comment by jlaine** [comment]
I think maybe a README.rst in the examples directory might be better. Just populate the DNS over QUIC part and I'll jump in and add docs for the rest

**Comment by ShuaiZhao** [comment]
@jlaine @tigertoes that will be great :)

**Comment by jlaine** [comment]
The PR put together by @tigertoes has been merged!

**Comment by ShuaiZhao** [comment]
Thanks @ALL
