### ISSUE TITLE
 Can you see the details of the quic packet?

### ISSUE THREAD

**Issue by kangprog** [aiortc/aioquic#97]
I want to see the details of quic's packet.

First, I ran the example with two vm.
http3.Server (ubuntu) http3.client (window10)

The packet I captured with wireshark (3.2) comes out as below.
![s1](https://user-images.githubusercontent.com/40859447/81000920-e0b36500-8e81-11ea-9dd7-dadadeca6236.PNG)

I would like to see the packets in detail like the address below.
https://twitter.com/Lekensteyn/status/975894492392902656/photo/1

Should I set tls.keylog_file?

**Comment by jlaine** [comment]
Yes, both the client and the server accept a `--secrets-log` argument: the path to which you want the TLS keys to be written. You can then use this log file to decrypt packets in Wireshark.
