### ISSUE TITLE
Streams should be deleted once they're no longer needed

### ISSUE THREAD

**Issue by vasilvv** [aiortc/aioquic#99]
I've tried writing some code that opened 100 of relatively short outgoing unidirectional streams per second.  It worked fine at first, but eventually got to the point where it consumed 100% of CPU and a gigabyte of RAM in a single connection.  A quick look at the code suggests that once a stream gets into QuicConnection._streams, it never gets removed, even when all of the data inside the stream has been acknowledged and there's no reason to keep it around.

**Comment by jlaine** [comment]
Hi Victor!

You are absolutely right, the current behaviour doesn't scale properly. I think there might be two things going on here:

- as you point out `_streams` is never purged. I need to re-read the specs to figure out how this would impact things like determining the next available stream ID, or respecting stream limits.

- probably more importantly:  the way I iterate over the streams to determine what data to send is most likely very inefficient with a "largish" number of streams: https://github.com/aiortc/aioquic/blob/300cf7d74bfa81321e91e8bc056a03abdd180245/src/aioquic/quic/connection.py#L2306

Do you have any suggestions on this second point?

**Comment by jlaine** [comment]
OK, now that we have a stream reset API in place, I'm keen to revisit this issue. I can understand why CPU usage is inefficient, but I'm puzzled by the RAM consumption. Do you have an example you could share for me to examine?
